"""Onboarding-quality golden assertion suite (Phase 0 / Lane II).

Strict, data-only assertions against the frozen
``tests/fixtures/onboarding_golden/`` fixture (live 2026-05-23 run
for david@szabostuban.com). Many of these tests **WILL FAIL** today —
that is deliberate. The failures ARE the spec the next phases close.

No LLM mocking, no monkeypatching, no source imports — these tests
read markdown + JSON off disk and assert quality rules grounded in
``packages/learn/docs/GENERATORS.md``.

Rule schema:
  Negative tests (junk MUST NOT appear) — 1-8
  Positive tests (gold MUST appear)     — 9-14
  Robustness placeholders (Phase 4)     — 15-16
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import pytest
import yaml

FIXTURE = Path(__file__).parent / "fixtures" / "onboarding_golden"
VAULT = FIXTURE / "vault"
ONBOARD = FIXTURE / "onboard" / "onboard.json"

# --------------------------------------------------------------------- helpers


def _parse_md(path: Path) -> tuple[dict[str, Any], str]:
    """Split a vault .md into (frontmatter_dict, body_str)."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)", text, re.DOTALL)
    if not m:
        return {}, text
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        fm = {}
    return (fm if isinstance(fm, dict) else {}), m.group(2)


def _records(record_type: str) -> list[tuple[Path, dict[str, Any], str]]:
    """Yield (path, frontmatter, body) for every record of one type."""
    out: list[tuple[Path, dict[str, Any], str]] = []
    d = VAULT / record_type
    if not d.exists():
        return out
    for p in sorted(d.glob("*.md")):
        if p.name == ".gitkeep":
            continue
        fm, body = _parse_md(p)
        out.append((p, fm, body))
    return out


def _name(fm: dict[str, Any], path: Path) -> str:
    return str(fm.get("name") or path.stem)


def _tokens(name: str) -> set[str]:
    return {t.lower() for t in re.findall(r"[A-Za-zÀ-ÿ0-9]+", name) if t}


def _token_overlap(a: str, b: str) -> float:
    ta, tb = _tokens(a), _tokens(b)
    if not ta or not tb:
        return 0.0
    inter = ta & tb
    return len(inter) / min(len(ta), len(tb))


# Service-summary-note regex (per GENERATORS.md §16).
_SERVICE_NOTE_RE = re.compile(
    r"^[A-Za-z0-9.\- ]+? (Service Emails( Summary)?|Email Digest"
    r"|Activity Summary|Notifications? Summary|Service & Notification Summary"
    r"|Service Relationship Overview|Emails and Updates"
    r"|Security Alerts|Billing Issue Notifications)\b",
    re.IGNORECASE,
)

# Domain-shape regex for org-name detection.
_DOMAIN_LIKE_RE = re.compile(r"\.(com|io|net|org|ai|co|so|hu|uk|de|us|app|dev)$", re.IGNORECASE)


# =============================================================================
# Negative: junk MUST NOT appear
# =============================================================================


def test_no_domain_stub_matters() -> None:
    """A matter whose name ends ' Project', has a `domain:` frontmatter key,
    AND has a body shorter than 300 chars is a `generate_matter_pack` fallback
    stub (packs.py:338) — KILL per GENERATORS.md §6.
    """
    offenders: list[str] = []
    for path, fm, body in _records("matter"):
        name = _name(fm, path)
        if (
            name.endswith(" Project")
            and "domain" in fm
            and len(body.strip()) < 300
        ):
            offenders.append(path.name)
    if offenders:
        pytest.fail(
            f"{len(offenders)} domain-stub matter records "
            f"(generate_matter_pack fallback junk): {offenders}"
        )


def test_no_inner_circle_autogenerated_matters() -> None:
    """A matter with `tier: inner_circle` AND an `Auto-generated` body is the
    same fallback's signature. The Opus matter generator never writes either
    marker.
    """
    offenders: list[str] = []
    for path, fm, body in _records("matter"):
        if str(fm.get("tier") or "").lower() == "inner_circle" and "Auto-generated" in body:
            offenders.append(path.name)
    if offenders:
        pytest.fail(
            f"{len(offenders)} inner_circle + 'Auto-generated' matters "
            f"(packs.py:338 fallback): {offenders}"
        )


def test_no_per_service_sender_notes() -> None:
    """No note whose name is a service-email-cluster summary.

    These come from the external alfred-vault curator over batch_processor's
    inbox drops (GENERATORS.md §16). Belongs in alfred-state.db.observation,
    not vault.
    """
    offenders: list[str] = []
    for path, fm, _ in _records("note"):
        name = _name(fm, path)
        if _SERVICE_NOTE_RE.match(name):
            offenders.append(name)
    if offenders:
        pytest.fail(
            f"{len(offenders)} service-summary notes (curator junk): "
            f"{offenders}"
        )


def test_no_near_duplicate_notes() -> None:
    """No two notes whose name-token overlap is >= 0.6 (e.g. the 4 GitHub
    summaries that all describe the same sender domain).
    """
    notes = [(_name(fm, p), p.name) for p, fm, _ in _records("note")]
    pairs: list[tuple[str, str, float]] = []
    for i, (na, fa) in enumerate(notes):
        for nb, fb in notes[i + 1:]:
            ov = _token_overlap(na, nb)
            if ov >= 0.6:
                pairs.append((fa, fb, round(ov, 2)))
    if pairs:
        pytest.fail(
            f"{len(pairs)} near-duplicate note pairs (overlap >= 0.6): "
            f"{pairs}"
        )


def test_no_non_human_persons() -> None:
    """No person whose name flags as non-human:
      - ends with 'Notification' / 'Notifications'
      - contains '@'
      - contains a domain-like substring ('.com', '.io', ...)
      - has only 1 capitalized token (likely truncation: 'David Szabo-St')
    """
    offenders: list[tuple[str, str]] = []
    for path, fm, _ in _records("person"):
        name = _name(fm, path)
        why: list[str] = []
        if re.search(r"\bnotifications?$", name, re.IGNORECASE):
            why.append("notifications-suffix")
        if "@" in name:
            why.append("contains-@")
        if _DOMAIN_LIKE_RE.search(name):
            why.append("domain-substring")
        caps = [t for t in name.split() if t[:1].isupper()]
        if len(caps) < 2:
            why.append("only-one-cap-token")
        if why:
            offenders.append((name, ",".join(why)))
    if offenders:
        pytest.fail(
            f"{len(offenders)} non-human / malformed person records: "
            f"{offenders}"
        )


def test_no_owner_duplicates() -> None:
    """No two person records with token-overlap >= 0.65 (one is a truncation
    or alias of the other), unless one declares the other in `aliases:`.

    Threshold 0.65 (not 0.7) because the live case 'David Szabo-St' vs
    'David Szabo-Stuban' tokenises to {david, szabo, st} vs
    {david, szabo, stuban} — overlap 0.667 (the hyphen splits the surname).
    """
    persons = [(_name(fm, p), fm, p.name) for p, fm, _ in _records("person")]
    offenders: list[tuple[str, str, float]] = []
    for i, (na, fma, fa) in enumerate(persons):
        for nb, fmb, fb in persons[i + 1:]:
            ov = _token_overlap(na, nb)
            if ov < 0.65:
                continue
            # explicit alias declared?
            aliases_a = [str(x).lower() for x in (fma.get("aliases") or [])]
            aliases_b = [str(x).lower() for x in (fmb.get("aliases") or [])]
            if nb.lower() in aliases_a or na.lower() in aliases_b:
                continue
            offenders.append((fa, fb, round(ov, 2)))
    if offenders:
        pytest.fail(
            f"{len(offenders)} duplicate-or-truncation person pairs: "
            f"{offenders}"
        )


def test_no_domain_only_orgs() -> None:
    """No org whose name is a bare domain (matches `\\.com$`, `\\.io$`, ...)
    UNLESS the same name token appears in vault/USER.md (legitimate context).
    """
    user_md_text = ""
    user_md = VAULT / "USER.md"
    if user_md.exists():
        user_md_text = user_md.read_text(encoding="utf-8").lower()
    offenders: list[str] = []
    for path, fm, _ in _records("org"):
        name = _name(fm, path)
        if _DOMAIN_LIKE_RE.search(name) and name.lower() not in user_md_text:
            offenders.append(name)
    if offenders:
        pytest.fail(f"{len(offenders)} domain-only orgs: {offenders}")


def test_instinct_confidence_grounded_in_observations() -> None:
    """No instinct with observation_count == 0 AND confidence_score >= 0.5.

    Day-zero instincts must start at the Asking tier; the discretion gate
    earns confidence from observed decisions, not from an LLM-stamped prior.
    See GENERATORS.md §7.
    """
    offenders: list[tuple[str, float, int]] = []
    for path, fm, _ in _records("instinct"):
        # input_patterns may be a JSON-string in the packs_opus path
        obs = fm.get("observation_count")
        conf = fm.get("confidence_score")
        try:
            obs_n = int(obs) if obs is not None else 0
        except (TypeError, ValueError):
            obs_n = 0
        try:
            conf_f = float(conf) if conf is not None else 0.0
        except (TypeError, ValueError):
            conf_f = 0.0
        if obs_n == 0 and conf_f >= 0.5:
            offenders.append((path.name, conf_f, obs_n))
    if offenders:
        pytest.fail(
            f"{len(offenders)} instincts with unearned confidence "
            f"(obs=0, conf>=0.5): {offenders}"
        )


# =============================================================================
# Positive: gold MUST appear
# =============================================================================


def test_at_least_eight_substantive_matters() -> None:
    """At least 8 matters whose body has a '## Context' section AND that
    section is >= 400 chars. These are the gold Opus-authored records.
    """
    good: list[str] = []
    for path, _, body in _records("matter"):
        m = re.search(r"## Context\s*\n+(.*?)(?=\n##\s|\Z)", body, re.DOTALL)
        if m and len(m.group(1).strip()) >= 400:
            good.append(path.name)
    if len(good) < 8:
        pytest.fail(
            f"Only {len(good)} substantive matters with ## Context >= 400 chars "
            f"(need >= 8): {good}"
        )


def test_principal_rules_md_exists() -> None:
    """vault/RULES.md must exist — written by personalize_opus
    (onboarding_v3.py:721) per its docstring contract.
    """
    p = VAULT / "RULES.md"
    if not p.exists():
        pytest.fail(
            "vault/RULES.md missing — personalize_opus contract is "
            "USER.md + SOUL.md + MEMORY.md + TOOLS.md + RULES.md but only "
            "USER.md is being written. See GENERATORS.md §3."
        )


def test_principal_soul_md_exists() -> None:
    """vault/SOUL.md must exist (same contract as RULES.md)."""
    p = VAULT / "SOUL.md"
    if not p.exists():
        pytest.fail(
            "vault/SOUL.md missing — personalize_opus contract violated. "
            "See GENERATORS.md §3."
        )


def test_day_one_desk_seeded() -> None:
    """The Desk must be non-empty on day one — at least 2 needs_attention
    records with `source: onboarding_seed`.
    """
    d = VAULT / "needs_attention"
    if not d.exists():
        pytest.fail(
            "vault/needs_attention/ directory missing — Desk lands empty "
            "on day one. GAP per GENERATORS.md §17."
        )
    seeded = 0
    for p in d.glob("*.md"):
        fm, _ = _parse_md(p)
        if str(fm.get("source") or "") == "onboarding_seed":
            seeded += 1
    if seeded < 2:
        pytest.fail(
            f"Only {seeded} onboarding_seed Desk cards (need >= 2). "
            f"GAP per GENERATORS.md §17."
        )


def test_orgs_include_real_companies() -> None:
    """Real companies named in gold matters / facts must be materialised as
    org records. At least 3 of {NeoTerra, Stylers, Keller Williams} required.
    """
    org_names = {_name(fm, p).lower() for p, fm, _ in _records("org")}
    expected = ["neoterra", "stylers", "keller williams"]
    missing = [e for e in expected if not any(e in n for n in org_names)]
    if len(expected) - len(missing) < 3:
        pytest.fail(
            f"Only {len(expected) - len(missing)}/3 expected orgs found. "
            f"Missing: {missing}. Have: {sorted(org_names)}. "
            f"See GENERATORS.md §12."
        )


def test_all_people_are_plausible_humans() -> None:
    """Every person record name must look like a real human: >= 2 capitalized
    tokens, no domain substring, no 'Notifications' suffix.
    """
    bad: list[str] = []
    for path, fm, _ in _records("person"):
        name = _name(fm, path)
        caps = [t for t in name.split() if t[:1].isupper()]
        if (
            len(caps) < 2
            or _DOMAIN_LIKE_RE.search(name)
            or re.search(r"\bnotifications?$", name, re.IGNORECASE)
        ):
            bad.append(name)
    if bad:
        pytest.fail(
            f"{len(bad)} implausible-human person records: {bad}. "
            f"See GENERATORS.md §12."
        )


# =============================================================================
# Robustness placeholders — Phase 4 (LLM mocking, not part of this commit)
# =============================================================================


def test_always_reaches_stage_done_even_with_402(tmp_path) -> None:
    """The pipeline must reach stage=done even when one or more Opus calls
    402 — degraded stages should be recorded, not abort.

    Phase 4 / Lane II — Commit 2. The ``_safe_stage_wrapper`` in the
    OnboardingPipeline workflow downgrades a residual activity exception
    (e.g. retries exhausted on a 402) to a stage-degrade record. The
    workflow always reaches ``stage=done``.

    This is a behavioural assertion against the wrapper itself rather
    than the full workflow (which would need ctrl-api + Hermes mocks
    larger than this commit's scope). It exercises the SAME contract
    the integration tests in ``test_onboarding_safe_stage`` cover.
    """
    from src.workflows.onboarding_pipeline import _record_stage_degrade

    onboard_path = tmp_path / "onboard.json"
    onboard_path.write_text(json.dumps({
        "user_id": "u-1",
        "stage": "metadata",
        "progress": {"current_day": 0, "total_days": 0,
                     "facts_count": 0, "patterns_count": 0},
    }))

    # Simulate: facts AND personalize both 402-exhaust; patterns succeeded.
    _record_stage_degrade(str(onboard_path), "facts",
                          "credits exhausted on extract_facts_opus")
    _record_stage_degrade(str(onboard_path), "personalize",
                          "credits exhausted on personalize_opus")

    data = json.loads(onboard_path.read_text())
    # The workflow's audit trail captures both degraded stages.
    assert "facts" in data.get("degraded_stages", [])
    assert "personalize" in data.get("degraded_stages", [])
    # And `patterns` is NOT marked — only failed stages are recorded.
    assert "patterns" not in data.get("degraded_stages", [])





def test_degraded_stages_field_present_on_402(tmp_path, monkeypatch) -> None:
    """On a 402 path the onboard.json must carry a ``degraded_stages: [...]``
    field listing which stages fell back to the rule-based generator, so the
    UI can surface 'finished with reduced fidelity' to the principal.

    Phase 4 / Lane II — Commit 1. The credit-aware degrade is wired into each
    LLM-calling onboarding activity; simulating a 402 via ``_call_llm`` must
    produce a ``degraded_stages`` entry without raising.
    """
    import asyncio
    from unittest.mock import AsyncMock, patch
    from typing import Any
    import httpx as _httpx
    from temporalio import activity as _activity
    from temporalio.testing import ActivityEnvironment as _ActivityEnvironment

    onboard_path = tmp_path / "onboard.json"
    onboard_path.write_text(json.dumps({
        "user_id": "u-1",
        "stage": "metadata",
        "progress": {"current_day": 0, "total_days": 0,
                     "facts_count": 0, "patterns_count": 0},
        "facts": [],
        "patterns": [],
        "emails": [{"date": "2026-05-20", "from": "x@y.com",
                    "to": "u@v.com", "subject": "s", "snippet": "hi"}],
        "user_md": "", "soul_md": "",
        "automations": [],
        "brief": "",
    }))

    req = _httpx.Request("POST", "http://hermes/v1/responses")
    resp = _httpx.Response(status_code=402, request=req,
                           json={"error": {"message": "insufficient credits"}})
    exc = _httpx.HTTPStatusError("402", request=req, response=resp)

    monkeypatch.setenv("AAS_API_KEY", "test-token")

    from src.activities.onboarding_v3 import extract_facts_opus

    env = _ActivityEnvironment()

    @_activity.defn(name="_q_wrap")
    async def _wrap() -> Any:
        return await extract_facts_opus(str(onboard_path))

    with patch("src.activities.onboarding_v3._call_llm",
               new=AsyncMock(side_effect=exc)):
        result = asyncio.run(env.run(_wrap))

    assert isinstance(result, dict) and result.get("degraded") is True, (
        "extract_facts_opus must return a degrade sentinel on 402, not raise"
    )
    data = json.loads(onboard_path.read_text())
    assert "facts" in data.get("degraded_stages", []), (
        f"onboard.json must carry degraded_stages with 'facts' — got "
        f"{data.get('degraded_stages')!r}"
    )


# Quick sanity: the fixture is wired correctly. If THIS test fails, the
# other tests' results are meaningless.
def test_fixture_is_present() -> None:
    assert FIXTURE.exists(), f"fixture missing at {FIXTURE}"
    assert ONBOARD.exists(), f"onboard.json missing at {ONBOARD}"
    with open(ONBOARD) as f:
        data = json.load(f)
    assert data.get("stage") == "done", (
        f"fixture onboard.json stage is {data.get('stage')!r}, expected 'done'"
    )
    assert len(data.get("emails", [])) >= 1000, (
        f"fixture only has {len(data.get('emails', []))} emails — expected 5000"
    )
