// envfile.mjs — parse and render the alfred-black .env.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { FIELDS } from './schema.mjs';

// Parse a .env into a plain { KEY: value } map. Tolerates `#KEY=` commented
// placeholders (treated as absent), `export KEY=`, quoted values, and last-
// assignment-wins.
export function parseEnv(path) {
  const out = {};
  if (!existsSync(path)) return out;
  const text = readFileSync(path, 'utf8');
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!m) continue;
    let val = m[2];
    // strip a single layer of matching quotes
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[m[1]] = val;
  }
  return out;
}

// Render the final .env from the answers map. Comment structure and variable
// ordering follow FIELDS (which mirrors .env.example).
export function renderEnv(answers) {
  const lines = [];
  lines.push('# alfred-black — environment.');
  lines.push('#');
  lines.push('# Generated by the alfred-black setup wizard (packages/setup).');
  lines.push('# Re-run `./scripts/setup.sh` to edit these values; it pre-fills');
  lines.push('# each prompt with what is already here and keeps existing secrets.');
  lines.push('#');
  lines.push('# The non-interactive path is still `cp .env.example .env` +');
  lines.push('# `./scripts/bootstrap.sh` — see README.');
  lines.push('');

  const blockHeader = {
    required:
      '# ════════════════════════════════════════════════════════════════════\n' +
      '# USER MUST FILL — required.\n' +
      '# ════════════════════════════════════════════════════════════════════',
    optional:
      '# ════════════════════════════════════════════════════════════════════\n' +
      '# USER MUST FILL — optional. Leave blank to disable the feature.\n' +
      '# ════════════════════════════════════════════════════════════════════',
    generated:
      '# ════════════════════════════════════════════════════════════════════\n' +
      '# AUTO-GENERATED — managed by the setup wizard. Do not edit by hand.\n' +
      '# Each is randomBytes(32).toString("hex"); existing values are kept.\n' +
      '# ════════════════════════════════════════════════════════════════════',
  };

  let currentBlock = null;
  for (const f of FIELDS) {
    if (f.block !== currentBlock) {
      currentBlock = f.block;
      lines.push(blockHeader[currentBlock]);
      lines.push('');
    }
    if (f.comment) {
      lines.push(f.comment);
    }
    const val = answers[f.key] ?? '';
    lines.push(`${f.key}=${val}`);
    lines.push('');
  }

  return lines.join('\n').replace(/\n+$/, '\n');
}

export function writeEnv(path, answers) {
  writeFileSync(path, renderEnv(answers), 'utf8');
}
