import fs from "node:fs";
import { addRoute } from "../server.js";
import { sendJson, ValidationError } from "../errors.js";
import { dockerComposeCmd, dockerExec, execAsync, sudoExec, parseJsonLines, validateServiceName, COMPOSE_DIR, HERMES_CMD, HERMES_CONTAINER } from "../helpers.js";
import { getVaultContextData, getInboxFiles, VAULT_PATH } from "./vault.js";
import { readDurableActivity } from "../activity.js";
import { queryAuditCrossTier } from "../../db/coldRead.js";
import { getStateDb } from "../../db/state.js";
import { getDiskInfo } from "../diskWatch.js";

// alfred-black mounts the alfred daemon's data dir as a named Docker volume
// (PLAN.md Part E), bind-mounted into ctrl-api at /alfred-data by default.
const ALFRED_DATA_DIR = process.env.ALFRED_DATA_DIR ?? "/alfred-data";
const CHORE_GENERATION_AUDIT_LOG = `${ALFRED_DATA_DIR}/chore-generation-audit.jsonl`;
const CHORE_VAULT_DIR = `${VAULT_PATH}/chore`;
const PROMOTION_DRAFTS_DIR = `${ALFRED_DATA_DIR}/promotion-drafts`;

const ENV_PATH = `${COMPOSE_DIR}/.env`;

// In-memory rate limit for the chore-specific learn restart route. Prevents
// thrashing when an onboarding generates multiple templates and each tries
// to trigger a restart. The limit is intentionally process-local — restarts
// during a stuck/looping container would be visible to ops via container
// uptime anyway.
let _lastLearnRestartAtMs = 0;
const _LEARN_RESTART_MIN_INTERVAL_MS = 30_000;

// Minimal scalar-frontmatter parser for the /audit endpoint. Only handles
// top-level `key: value` and `key: "quoted"` — everything else (nested,
// lists) is ignored. We just need a few summary-bearing keys.
function parseSimpleYaml(raw: string): Record<string, any> {
  const out: Record<string, any> = {};
  for (const line of raw.split("\n")) {
    if (!line || line.startsWith("#")) continue;
    if (/^\s/.test(line)) continue; // skip indented (nested) lines
    const idx = line.indexOf(":");
    if (idx < 1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (val === "null" || val === "~" || val === "") continue;
    out[key] = val;
  }
  return out;
}

// Audit kind classification from filename prefix. The frontmatter `type`
// field is the canonical answer when present; this function exists for
// (a) the pre-stat filename filter (we don't want to read frontmatter
// just to know what kind something is), and (b) a fallback when fm.type
// is missing. Returns "" if nothing matches.
function classifyAuditKind(filename: string): string {
  const KINDS = [
    "steward-action-reversed",
    "steward-action",
    "steward-source-pruned",
    "signal-action",
    "needs_attention_action",
    "desk-action",
    "auto-task-created",
  ];
  for (const k of KINDS) {
    if (filename.startsWith(`${k}-`) || filename === `${k}.md`) return k;
  }
  return "";
}

// Steward-action + steward-source-pruned are auto-generated by the
// steward bot — every existing task gets a health-check ping written
// on every steward pass. 94% of audit volume, ~0% of audit signal.
// Hide by default; surface when ?include_automated=1.
function isAutomatedAuditKind(filename: string): boolean {
  const k = classifyAuditKind(filename);
  return k === "steward-action" || k === "steward-source-pruned";
}

// Cheap per-needs_attention headline lookup. Used by the desk-action
// + needs_attention_action formatters so the summary can read
// "Delegated 'Plex Pass expired — renew to keep it active'" instead of
// the raw needs_attention id. Reads only the linked record's
// frontmatter, returns "" on miss.
function readNeedsAttentionHeadline(refOrId: string): string {
  if (!refOrId) return "";
  // Accept either "needs_attention/<id>.md" or a bare id.
  const id = refOrId
    .replace(/^needs_attention\//, "")
    .replace(/\.md$/, "")
    .trim();
  if (!id) return "";
  try {
    const raw = fs.readFileSync(
      `${VAULT_PATH}/needs_attention/${id}.md`,
      "utf-8",
    );
    const m = /^---\n([\s\S]*?)\n---/.exec(raw);
    if (!m) return "";
    const fm = parseSimpleYaml(m[1]);
    return (
      String(fm.display_headline || fm.action_what || "").trim() || ""
    );
  } catch {
    return "";
  }
}

function quote(s: string): string {
  return s ? `"${s.replace(/"/g, "'")}"` : "";
}

// Build a human sentence for the audit row, dispatching per kind. Each
// formatter assumes the frontmatter we've already read (top-level
// scalars only — see parseSimpleYaml). Falls back to a sane generic
// rendering when a kind isn't specifically handled.
function formatAuditSummary(
  kind: string,
  fm: Record<string, any>,
  filename: string,
): string {
  switch (kind) {
    case "signal-action": {
      const chosen = String(fm.chosen_path || "").trim();
      const reason = String(fm.decision_reason || "").trim();
      const verb =
        chosen === "agent" ? "Dispatched signal to agent" : "Routed signal to your desk";
      return reason ? `${verb} — ${reason.replace(/_/g, " ")}` : verb;
    }

    case "needs_attention_action": {
      // Frontmatter has: action (dispatched/skipped/done), note, target.
      const action = String(fm.action || "").trim();
      const headline = readNeedsAttentionHeadline(
        String(fm.target || ""),
      );
      const verb = action ? toSentenceVerb(action) : "Resolved";
      const subject = headline ? ` ${quote(headline)}` : "";
      const note = String(fm.note || "").trim();
      const noteTail = note ? ` — ${quote(note)}` : "";
      return `${verb}${subject}${noteTail}`;
    }

    case "desk-action":
    case "desk_action": {
      // Frontmatter: action (delegate/defer/delete/do/noise), source,
      // source_id, note.
      const action = String(fm.action || "").trim();
      const source = String(fm.source || "").trim();
      const headline =
        source === "needs_attention"
          ? readNeedsAttentionHeadline(String(fm.source_id || ""))
          : "";
      const verbMap: Record<string, string> = {
        delegate: "Delegated",
        defer: "Deferred",
        delete: "Marked done",
        do: "Took on",
        noise: "Marked noise",
      };
      const verb = verbMap[action] || (action ? toSentenceVerb(action) : "Acted on");
      const subject = headline
        ? ` ${quote(headline)}`
        : source
          ? ` a ${source.replace(/_/g, " ")} card`
          : "";
      const note = String(fm.note || "").trim();
      const noteTail = note ? ` — ${quote(note)}` : "";
      return `${verb}${subject}${noteTail}`;
    }

    case "auto-task-created": {
      const title = String(fm.title || "").trim();
      return title ? `Auto-created task: ${title}` : "Auto-created a task";
    }

    case "steward-action": {
      const decision = String(fm.decision || "").trim();
      // Filename has the task slug embedded after the sha — drop the
      // sha + dash, capitalize first letter, replace dashes with spaces.
      const base = filename.replace(/\.md$/, "");
      const m = base.match(
        /^steward-action-\d{4}-\d{2}-\d{2}T[\d-]+Z-[0-9a-f]+-(.+)$/i,
      );
      const subject = m ? sentenceCase(m[1].replace(/-/g, " ")) : "a task";
      const tail = decision
        ? ` — ${decision.replace(/_/g, " ")}`
        : "";
      return `Reviewed "${subject}"${tail}`;
    }

    case "steward-source-pruned":
      return "Pruned stale evidence";

    case "steward-action-reversed":
      return "Reversed a steward action";

    default: {
      // Generic fallback for unknown kinds: try fm summary, fall back
      // to a cleaned-up filename.
      const candidates = [
        fm.summary,
        fm.description,
        fm.headline,
        fm.action_what,
        fm.what,
        fm.title,
        fm.note,
        fm.message,
      ];
      for (const c of candidates) {
        if (typeof c === "string" && c.trim()) return c.trim();
      }
      const base = filename.replace(/\.md$/, "");
      const m = base.match(/^([a-z_]+(?:-action)?)-?\d{4}-\d{2}-\d{2}T[\d-]+Z-(.+)$/i);
      if (m) return `${m[1]} — ${m[2].replace(/-/g, " ")}`;
      return base.replace(/-/g, " ");
    }
  }
}

function sentenceCase(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}

function toSentenceVerb(action: string): string {
  if (!action) return "";
  // Map common past-tense action labels — "dispatched" stays, "done"
  // becomes "Marked done", etc.
  const map: Record<string, string> = {
    dispatched: "Dispatched",
    skipped: "Deferred",
    done: "Marked done",
  };
  return map[action] || sentenceCase(action);
}

// F4/C12 — `state.db audit` SQL-ledger read helpers. Compare action_type on a
// hyphen/underscore-stripped lowercase form so mixed casing across writers
// (`signal-action` vs `desk_action`) doesn't fragment the filter (F5 also
// normalises at the write boundary). Automated/internal rows hidden by default:
// steward noise (94% of volume), signal-router actions, and the
// needs_attention_action/desk_action twins already represented first-class by
// the `decision` row (C12: one row per user action).
const canonAuditType = (t: string) => String(t ?? "").toLowerCase().replace(/[_-]/g, "");
const AUTOMATED_AUDIT_TYPES = new Set(
  ["steward-action", "steward-source-pruned", "steward-action-reversed",
   "signal-action", "auto-task-created", "needs_attention_action", "desk_action"]
    .map(canonAuditType),
);
const isAutomatedAuditType = (t: string) => AUTOMATED_AUDIT_TYPES.has(canonAuditType(t));

function toC12AuditItem(row: Record<string, any>): Record<string, unknown> {
  const parse = (v: unknown): any => {
    if (v == null) return null;
    if (typeof v !== "string") return v;
    try { return JSON.parse(v); } catch { return v; }
  };
  const changes = parse(row.changes_json) ?? {};
  const payload = parse(row.payload_json) ?? {};
  const note = changes?.note ?? payload?.note ?? null;
  const reversible = parse(row.undo_json) != null || payload?.is_reversible === true;
  const reversedAt = changes?.reversed_at ?? payload?.reversed_at ?? null;
  return {
    id: row.id, ts: row.ts, action_type: row.action_type,
    actor: row.actor ?? null, headline: row.summary ?? null,
    note: note != null ? String(note) : null, source: row.source ?? null,
    reversible: Boolean(reversible),
    reversed_at: reversedAt != null ? String(reversedAt) : null,
  };
}

export function registerAdminRoutes(): void {
  // --- Containers ---

  // List containers
  addRoute("GET", "/api/v1/admin/containers", async ({ res }) => {
    const stdout = await dockerComposeCmd(["ps", "--format", "json"]);
    sendJson(res, 200, parseJsonLines(stdout));
  });

  // Restart container
  addRoute("POST", "/api/v1/admin/containers/:service/restart", async ({ res, params, req }) => {
    validateServiceName(params.service);
    // Guardrail #3 — self-lockout refusal.
    // Restarting `hermes` kills the running session; restarting `ctrl-api`
    // kills the API connection mid-request. Both are allowed, but require an
    // explicit opt-in header so an agent can't accidentally lock itself out.
    const SELF_RESTART_SERVICES = ["hermes", "ctrl-api"];
    if (SELF_RESTART_SERVICES.includes(params.service)) {
      const confirmHeader = req.headers["x-confirm-self-restart"];
      if (confirmHeader !== "yes") {
        sendJson(res, 409, {
          error: `Refusing to restart ${params.service} without X-Confirm-Self-Restart:yes header — this kills the running session or API connection`,
        });
        return;
      }
    }
    await dockerComposeCmd(["restart", params.service]);
    sendJson(res, 200, { message: `Container "${params.service}" restarted` });
  });

  // Stop container
  addRoute("POST", "/api/v1/admin/containers/:service/stop", async ({ res, params }) => {
    validateServiceName(params.service);
    await dockerComposeCmd(["stop", params.service]);
    sendJson(res, 200, { message: `Container "${params.service}" stopped` });
  });

  // Start container
  addRoute("POST", "/api/v1/admin/containers/:service/start", async ({ res, params }) => {
    validateServiceName(params.service);
    await dockerComposeCmd(["start", params.service]);
    sendJson(res, 200, { message: `Container "${params.service}" started` });
  });

  // Container logs (non-streaming)
  addRoute("GET", "/api/v1/admin/containers/:service/logs", async ({ res, params, query }) => {
    validateServiceName(params.service);
    const tail = query.get("tail") ?? "100";
    if (!/^\d+$/.test(tail)) throw new ValidationError("tail must be a number");
    const stdout = await dockerComposeCmd(["logs", "--tail", tail, params.service]);
    sendJson(res, 200, { logs: stdout });
  });

  // Chore-specific alfred-learn restart with rate limiting.
  //
  // The chore generation pipeline (Step 4) calls this after writing a
  // generated template to /alfred-data/user-chores/ so the worker re-imports
  // its module list and picks up the new template. The rate limit prevents
  // thrashing when an onboarding generates multiple templates back-to-back
  // and each tries to trigger a restart.
  //
  // Returns:
  //   200 { ok, restarted_at, ready_after_seconds }
  //   429 { error: "rate limited", retry_after_seconds }
  //   500 { error: <docker error> }
  addRoute("POST", "/api/v1/admin/restart-learn", async ({ res }) => {
    const now = Date.now();
    const elapsed = now - _lastLearnRestartAtMs;
    if (_lastLearnRestartAtMs > 0 && elapsed < _LEARN_RESTART_MIN_INTERVAL_MS) {
      const retryAfter = Math.ceil((_LEARN_RESTART_MIN_INTERVAL_MS - elapsed) / 1000);
      sendJson(res, 429, {
        error: "rate limited",
        retry_after_seconds: retryAfter,
        message: "alfred-learn was restarted recently — wait before triggering another",
      });
      return;
    }
    _lastLearnRestartAtMs = now;

    const startedAt = new Date().toISOString();
    try {
      await dockerComposeCmd(["restart", "alfred-learn"]);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      sendJson(res, 500, { error: "restart failed", details: message });
      return;
    }

    // Best-effort wait for the container to be back in 'running' state.
    // Capped at 60 seconds. We don't poll healthchecks because alfred-learn
    // doesn't have one defined — Temporal heartbeats provide health visibility
    // through other channels.
    const deadline = Date.now() + 60_000;
    let readyAfterMs = 0;
    while (Date.now() < deadline) {
      try {
        const stdout = await dockerComposeCmd([
          "ps",
          "--format",
          "json",
          "alfred-learn",
        ]);
        // Each line is a JSON record. We just need to find the alfred-learn
        // entry and verify its State === "running".
        let isRunning = false;
        for (const line of stdout.split("\n")) {
          const trimmed = line.trim();
          if (!trimmed) continue;
          try {
            const obj = JSON.parse(trimmed);
            if (obj.Service === "alfred-learn" && obj.State === "running") {
              isRunning = true;
              break;
            }
          } catch {
            // ignore non-JSON lines
          }
        }
        if (isRunning) {
          readyAfterMs = Date.now() - now;
          break;
        }
      } catch {
        // ignore poll errors and try again
      }
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    sendJson(res, 200, {
      ok: true,
      restarted_at: startedAt,
      ready_after_seconds: Math.round(readyAfterMs / 1000),
    });
  });

  // --- S4-10: chore generation audit log ---
  //
  // Returns recent entries from /alfred-data/chore-generation-audit.jsonl,
  // which is written by the deploy activity (and the S4-8 generation
  // chain in the onboarding pipeline). One JSON line per deployment
  // event, containing phase/status/module_name/workflow_class_name/
  // source_hash/path/bytes/timestamp.
  //
  // Query params:
  //   limit: max number of entries to return (default 50, cap 500)
  //   since: ISO timestamp — skip entries with earlier timestamps
  //
  // Returns:
  //   200 { entries: Entry[], total_lines_scanned: number, truncated: bool }
  addRoute("GET", "/api/v1/admin/chore-generation-audit", async ({ res, query }) => {
    const AUDIT_LOG_PATH = CHORE_GENERATION_AUDIT_LOG;

    let limit = 50;
    const limitRaw = query.get("limit");
    if (limitRaw !== null) {
      if (!/^\d+$/.test(limitRaw)) {
        throw new ValidationError("limit must be a non-negative integer");
      }
      limit = Math.min(parseInt(limitRaw, 10), 500);
    }

    // Parse the since filter as a unix timestamp (seconds). The audit
    // log stores timestamps as epoch seconds via time.time() in Python.
    let sinceEpoch: number | null = null;
    const sinceRaw = query.get("since");
    if (sinceRaw) {
      const parsed = Date.parse(sinceRaw);
      if (isNaN(parsed)) {
        throw new ValidationError("since must be a valid ISO timestamp");
      }
      sinceEpoch = parsed / 1000;
    }

    if (!fs.existsSync(AUDIT_LOG_PATH)) {
      sendJson(res, 200, {
        entries: [],
        total_lines_scanned: 0,
        truncated: false,
        note: "audit log does not exist yet — no generation events recorded",
      });
      return;
    }

    // Read the whole file (it's rotated by nightly_maintenance so it
    // stays bounded). Parse each line as JSON, filter, and take the
    // last `limit` entries.
    const content = fs.readFileSync(AUDIT_LOG_PATH, "utf-8");
    const lines = content.split("\n").filter((l) => l.trim().length > 0);
    const entries: Array<Record<string, unknown>> = [];
    for (const line of lines) {
      try {
        const entry = JSON.parse(line) as Record<string, unknown>;
        if (sinceEpoch !== null) {
          const ts = entry.timestamp;
          if (typeof ts === "number" && ts < sinceEpoch) continue;
        }
        entries.push(entry);
      } catch {
        // skip malformed lines
      }
    }

    // Return newest-first, capped at limit
    entries.reverse();
    const truncated = entries.length > limit;
    sendJson(res, 200, {
      entries: entries.slice(0, limit),
      total_lines_scanned: lines.length,
      truncated,
    });
  });

  // --- S4-10: emergency-pause-all for chores ---
  //
  // Lists every chore record in vault/chore/ and pauses its Temporal
  // schedule + flips the vault record status to "paused". Used for
  // incident response: if a recent deployment or config change causes
  // chores to misbehave, pause everything at once, investigate, and
  // resume individually.
  //
  // This route is a best-effort batch operation. Failures on individual
  // chores are collected and returned in the response — the overall
  // call still returns 200 as long as SOMETHING paused.
  //
  // Returns:
  //   200 { paused: string[], failed: {slug, error}[], total: number }
  addRoute("POST", "/api/v1/admin/chores/emergency-pause-all", async ({ res }) => {
    const CHORE_DIR = CHORE_VAULT_DIR;
    if (!fs.existsSync(CHORE_DIR)) {
      sendJson(res, 200, {
        paused: [],
        failed: [],
        total: 0,
        note: "no chore directory — nothing to pause",
      });
      return;
    }

    const files = fs
      .readdirSync(CHORE_DIR)
      .filter((name) => name.endsWith(".md"));
    const paused: string[] = [];
    const failed: Array<{ slug: string; error: string }> = [];

    for (const filename of files) {
      const slug = filename.replace(/\.md$/, "");
      try {
        // Pause the Temporal schedule (best-effort). If the schedule
        // doesn't exist we still want to flip the vault status so the
        // state converges.
        try {
          await dockerExec("temporal", [
            "temporal",
            "schedule",
            "toggle",
            "--schedule-id",
            `chore-${slug}`,
            "--pause",
            "--reason",
            "emergency-pause-all",
          ]);
        } catch (err) {
          // Don't bail — still try to flip the vault status below.
          const msg = err instanceof Error ? err.message : String(err);
          if (!msg.includes("not found") && !msg.includes("NotFound")) {
            // Unknown schedule error — record it but continue
            failed.push({ slug, error: `schedule toggle: ${msg}` });
            continue;
          }
        }

        // Flip the vault record status to paused. Uses the same
        // in-place replace pattern as the single pause route in
        // chores.ts — safe because we only touch the status: line
        // inside the frontmatter block.
        const fp = `${CHORE_DIR}/${filename}`;
        const content = fs.readFileSync(fp, "utf-8");
        const end = content.indexOf("\n---", 3);
        if (end === -1) {
          failed.push({ slug, error: "no frontmatter terminator" });
          continue;
        }
        const fmBlock = content.slice(0, end);
        const rest = content.slice(end);
        const updated = fmBlock.replace(/^status:\s*.*$/m, "status: paused");
        fs.writeFileSync(fp, updated + rest, "utf-8");

        paused.push(slug);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        failed.push({ slug, error: msg });
      }
    }

    sendJson(res, 200, {
      paused,
      failed,
      total: files.length,
    });
  });

  // --- S5-3: list pending promotion drafts ---
  //
  // Lists every draft file in /mnt/encrypted/alfred/promotion-drafts/
  // so operators can see what the weekly reflection workflow (S5-2)
  // has staged for potential GitHub PR creation. Each draft is a JSON
  // file written by save_promotion_draft.
  //
  // Returns:
  //   200 {
  //     drafts: [
  //       {
  //         draft_id: string,  // filename stem
  //         module_name: string,
  //         workflow_class_name: string,
  //         pr_title: string,
  //         drafted_at: number,  // epoch seconds
  //         candidate_stats: { total_runs, live_runs, ... },
  //         source_bytes: number,
  //       }
  //     ],
  //     total: number,
  //   }
  addRoute("GET", "/api/v1/admin/chore-promotions", async ({ res }) => {
    if (!fs.existsSync(PROMOTION_DRAFTS_DIR)) {
      sendJson(res, 200, {
        drafts: [],
        total: 0,
        note: "no promotion-drafts directory — reflection workflow hasn't drafted anything yet",
      });
      return;
    }

    const files = fs
      .readdirSync(PROMOTION_DRAFTS_DIR)
      .filter((name) => name.endsWith(".json"));

    const drafts: Array<Record<string, unknown>> = [];
    for (const filename of files) {
      const draftId = filename.replace(/\.json$/, "");
      const fp = `${PROMOTION_DRAFTS_DIR}/${filename}`;
      try {
        const content = fs.readFileSync(fp, "utf-8");
        const parsed = JSON.parse(content) as Record<string, unknown>;
        const pythonSource = typeof parsed.python_source === "string"
          ? parsed.python_source
          : "";
        drafts.push({
          draft_id: draftId,
          module_name: parsed.module_name ?? null,
          workflow_class_name: parsed.workflow_class_name ?? null,
          pr_title: parsed.pr_title ?? null,
          drafted_at: parsed.drafted_at ?? null,
          candidate_stats: parsed.candidate_stats ?? null,
          source_bytes: pythonSource.length,
        });
      } catch (err) {
        // Malformed or unreadable drafts are still listed so operators
        // can manually inspect/delete them. Include the error for context.
        drafts.push({
          draft_id: draftId,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    // Newest first by drafted_at (falls back to filename sort for entries
    // without a timestamp — shouldn't happen but be defensive)
    drafts.sort((a, b) => {
      const ta = typeof a.drafted_at === "number" ? a.drafted_at : 0;
      const tb = typeof b.drafted_at === "number" ? b.drafted_at : 0;
      return tb - ta;
    });

    sendJson(res, 200, { drafts, total: drafts.length });
  });

  // --- Activity Feed ---

  addRoute("GET", "/api/v1/admin/activity", async ({ res, query }) => {
    const limit = Math.min(parseInt(query.get("limit") ?? "50", 10), 200);
    if (isNaN(limit) || limit < 1) throw new ValidationError("limit must be a positive number");
    sendJson(res, 200, readDurableActivity(limit));
  });

  // GET /api/v1/admin/audit?limit&include_automated=0&cursor=<ts> — the durable
  // audit ledger (/study#audit). F4/C12: reads the `state.db audit` SQL ledger
  // via the cross-tier (hot+cold) queryAuditCrossTier plumbing, NOT the legacy
  // vault/event/*.md walk (a subset that never surfaced first-class `decision`
  // rows and double-counted each click). One row per user action.
  addRoute("GET", "/api/v1/admin/audit", async ({ res, query }) => {
    const limit = Math.min(Math.max(parseInt(query.get("limit") ?? "50", 10) || 50, 1), 200);
    const includeAutomated = ["1", "true", "yes"].includes(
      (query.get("include_automated") ?? "").toLowerCase(),
    );
    // cursor = ts of the previous page's last item (exclusive upper bound).
    // Over-fetch when hiding automated rows so a full page survives the filter.
    const cursor = query.get("cursor");
    let result;
    try {
      result = queryAuditCrossTier({
        until: cursor || null, limit: includeAutomated ? limit : limit * 4, offset: 0,
      } as any);
    } catch {
      // The cold archive is optional for serving current data. If it is
      // temporarily unavailable, preserve the hot audit ledger instead of
      // turning a healthy state.db into an empty activity feed.
      try {
        const where = cursor ? "WHERE ts <= ?" : "";
        const args = cursor ? [cursor] : [];
        const fetchLimit = includeAutomated ? limit : limit * 4;
        const db = getStateDb();
        const entries = db.prepare(
          `SELECT * FROM audit ${where} ORDER BY ts DESC LIMIT ?`,
        ).all(...args, fetchLimit) as Array<Record<string, unknown>>;
        const total = (db.prepare(
          `SELECT COUNT(*) AS n FROM audit ${where}`,
        ).get(...args) as { n: number }).n;
        result = { entries, total };
      } catch {
        sendJson(res, 200, { items: [], total: 0, next_cursor: null });
        return;
      }
    }
    const visible = (result.entries as Array<Record<string, any>>).filter(
      (row) => includeAutomated || !isAutomatedAuditType(String(row.action_type ?? "")),
    );
    const page = visible.slice(0, limit);
    const last = page.length ? page[page.length - 1] : null;
    sendJson(res, 200, {
      items: page.map(toC12AuditItem),
      total: result.total,
      next_cursor: visible.length > limit && last ? String(last.ts) : null,
    });
  });

  // --- Config ---

  // Read .env (filtering out AAS_API_KEY)
  addRoute("GET", "/api/v1/admin/config/env", async ({ res }) => {
    let content = "";
    try {
      content = fs.readFileSync(ENV_PATH, "utf-8");
    } catch {
      sendJson(res, 200, { env: {} });
      return;
    }
    const env: Record<string, string> = {};
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx < 0) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const value = trimmed.slice(eqIdx + 1).trim();
      if (key === "AAS_API_KEY") continue; // never expose the API key
      env[key] = value;
    }
    sendJson(res, 200, { env });
  });

  // Update .env (surgical patch — preserves comments, blank lines, ordering)
  addRoute("PATCH", "/api/v1/admin/config/env", async ({ res, body }) => {
    const b = body as Record<string, string | null> | undefined;
    if (!b || typeof b !== "object") throw new ValidationError("Request body must be an object of key-value pairs");

    // Prevent overwriting the API key
    if ("AAS_API_KEY" in b) throw new ValidationError("Cannot modify AAS_API_KEY via API");

    let lines: string[];
    try {
      lines = fs.readFileSync(ENV_PATH, "utf-8").split("\n");
    } catch {
      lines = [];
    }

    const remaining = new Map(Object.entries(b));

    // Update or remove existing lines
    const result = lines.map((line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) return line;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx < 0) return line;
      const key = trimmed.slice(0, eqIdx).trim();
      if (!remaining.has(key)) return line;
      const newValue = remaining.get(key);
      remaining.delete(key);
      if (newValue === null) return null; // remove line
      return `${key}=${newValue}`;
    }).filter((line): line is string => line !== null);

    // Append any new keys not already in the file
    for (const [key, value] of remaining) {
      if (value !== null) {
        result.push(`${key}=${value}`);
      }
    }

    const content = result.join("\n");
    fs.writeFileSync(ENV_PATH, content.endsWith("\n") ? content : content + "\n", "utf-8");
    sendJson(res, 200, { message: "Environment updated", keys: Object.keys(b) });
  });

  // --- Hermes config GET/PATCH: REMOVED (issue #59) ---
  //
  // The `GET`/`PATCH /api/v1/admin/config/openclaw` routes were dead
  // phantom-config machinery, the same class #44 removed from
  // integrations.ts. They read/backed-up/deep-merge-wrote a `config.yaml`
  // at `/hermes-data/main/config.yaml` — a path that does not exist (the
  // real layout is `${HERMES_HOME}/profiles/<profile>/config.yaml`,
  // HERMES_HOME=/opt/data). No caller used either route: the GET had zero
  // consumers in web or mcp-server, and the PATCH hand-edited a config
  // Hermes owns and regenerates from a template (hermes-config.yaml.njk) —
  // the native write path is `hermes config set`. Removed rather than
  // path-corrected: there is nothing for ctrl-api to mediate here.

  // --- Ephemeral agents: REMOVED (PLAN.md Part F, issue #15) ---
  //
  // The `openclaw-workers/agents` GET/POST/DELETE routes are gone. Under
  // Hermes an ephemeral executor is a single `POST /v1/runs` against the
  // workers profile with session_id = `exec-<hash>` — there is no
  // create-config / hot-reload / delete-config dance, so there is nothing
  // for ctrl-api to mediate. In-flight ephemeral runs are listed via
  // GET /api/v1/hermes/agents/ephemeral (routes/hermes.ts).

  // --- Tailscale ---

  // Tailscale status
  addRoute("GET", "/api/v1/admin/tailscale/status", async ({ res }) => {
    const stdout = await execAsync("tailscale", ["status", "--json"]).then(r => r.stdout);
    sendJson(res, 200, JSON.parse(stdout));
  });

  // Tailscale serve status
  addRoute("GET", "/api/v1/admin/tailscale/serve", async ({ res }) => {
    const stdout = await sudoExec("tailscale", ["serve", "status", "--json"]);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // Regenerate TLS cert
  addRoute("POST", "/api/v1/admin/tailscale/cert", async ({ res }) => {
    const statusRaw = await execAsync("tailscale", ["status", "--json"]).then(r => r.stdout);
    const status = JSON.parse(statusRaw);
    const hostname = status.Self?.DNSName?.replace(/\.$/, "");
    if (!hostname) throw new ValidationError("Could not determine Tailscale hostname");
    await sudoExec("tailscale", ["cert", hostname]);
    sendJson(res, 200, { message: `Certificate regenerated for ${hostname}` });
  });

  // --- Combined dashboard endpoint (single round-trip) ---

  addRoute("GET", "/api/v1/admin/dashboard", async ({ res }) => {
    // Run all async operations in parallel to minimise total wait time
    const [healthResult, containersResult, pairingResult] = await Promise.allSettled([
      execAsync("/opt/alfred/healthcheck.sh", []).then(r => JSON.parse(r.stdout.trim())),
      dockerComposeCmd(["ps", "--format", "json"]).then(s => parseJsonLines(s)),
      // Hermes-native DM pairing (issue #42). `pairing list` emits
      // human-readable text — there is no JSON output — so the dashboard
      // carries the raw CLI text as a read-only status surface.
      dockerExec(HERMES_CONTAINER, [...HERMES_CMD, "-p", "main", "pairing", "list"]).then(s => ({ raw: s.trim() })),
    ]);

    // Fast synchronous reads
    const vaultRaw = getVaultContextData();
    const inboxFiles = getInboxFiles();
    const activityHealth = readDurableActivity(1);
    const rawHealth = healthResult.status === "fulfilled" && healthResult.value &&
      typeof healthResult.value === "object" ? healthResult.value : {};
    const health = {
      ...rawHealth,
      status: healthResult.status === "fulfilled" && !activityHealth.partial ? "ok" : "degraded",
    };

    // NOTE (issue #59): the legacy `openclawCfg` field is gone. It read
    // `/hermes-data/main/config.yaml` — a nonexistent path — so it was
    // always `{}`, and its only consumer (web `getDashboardData`) used it
    // solely to pull `gateway.auth.token`, an OpenClaw-era key Hermes' YAML
    // schema does not define (hermes-config.yaml.njk has no `gateway`
    // block). The field carried no real data; the web reader is updated to
    // match.

    sendJson(res, 200, {
      health,
      containers: containersResult.status === "fulfilled" ? containersResult.value : null,
      pairing: pairingResult.status === "fulfilled" ? pairingResult.value : null,
      vault: vaultRaw,
      inbox: { files: inboxFiles },
    });
  });

  // --- Health ---

  addRoute("GET", "/api/v1/admin/health", async ({ res }) => {
    // The packaged healthcheck script is provisioned by cloud-init and is
    // simply absent on stacks deployed another way. Its absence must degrade
    // the payload, not 500 the one aggregate-health surface operators have
    // (#310) — fall back to live container state.
    let stdout: string;
    try {
      stdout = await execAsync("/opt/alfred/healthcheck.sh", []).then(r => r.stdout);
    } catch (err: any) {
      const containers = await dockerComposeCmd(["ps", "--format", "json"])
        .then(s => parseJsonLines(s))
        .catch(() => null);
      sendJson(res, 200, {
        status: "degraded",
        script: "unavailable",
        detail: String(err?.message ?? err).slice(0, 200),
        containers,
      });
      return;
    }
    try {
      sendJson(res, 200, JSON.parse(stdout.trim()));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // --- Diagnostics ---

  // Echo request headers back (to verify what actually arrives at the ctrl API)
  addRoute("GET", "/api/v1/admin/debug/headers", async ({ req, res }) => {
    sendJson(res, 200, {
      method: req.method,
      url: req.url,
      httpVersion: req.httpVersion,
      headers: req.headers,
      terminalReady: (globalThis as any).__terminalReady ?? "not_set",
      terminalError: (globalThis as any).__terminalError ?? null,
    });
  });

  // --- System info ---

  addRoute("GET", "/api/v1/admin/system-info", async ({ res }) => {
    sendJson(res, 200, await getDiskInfo());
  });

  addRoute("GET", "/api/v1/admin/system/info", async ({ res }) => {
    const [uptimeResult, diskResult, memResult] = await Promise.all([
      execAsync("uptime", ["-p"]).then(r => r.stdout.trim()).catch(() => "unknown"),
      execAsync("df", ["-h", "/mnt/encrypted"]).then(r => r.stdout.trim()).catch(() => "unknown"),
      execAsync("free", ["-m"]).then(r => r.stdout.trim()).catch(() => "unknown"),
    ]);
    sendJson(res, 200, { uptime: uptimeResult, disk: diskResult, memory: memResult });
  });

  // --- Backups ---

  // Trigger backup (fire-and-forget)
  addRoute("POST", "/api/v1/admin/backups/trigger", async ({ res }) => {
    execAsync("sudo", ["bash", "/opt/alfred/backup.sh"], 600_000).catch((err) => {
      console.error("Backup failed:", err.message);
    });
    sendJson(res, 202, { message: "Backup triggered" });
  });

  // List backup snapshots
  addRoute("GET", "/api/v1/admin/backups/snapshots", async ({ res }) => {
    const stdout = await execAsync("bash", [
      "-c",
      "set -a && source /opt/alfred/restic.env && restic snapshots --json",
    ], 60_000).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // --- Temporal cluster ---

  addRoute("GET", "/api/v1/admin/temporal/cluster", async ({ res }) => {
    const stdout = await execAsync("docker", [
      "compose", "-f", `${COMPOSE_DIR}/docker-compose.yaml`,
      "exec", "-T", "temporal", "temporal", "operator", "cluster", "describe", "--output", "json",
    ]).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // Task queue describe
  addRoute("GET", "/api/v1/admin/temporal/task-queues/:name", async ({ res, params }) => {
    const stdout = await execAsync("docker", [
      "compose", "-f", `${COMPOSE_DIR}/docker-compose.yaml`,
      "exec", "-T", "temporal", "temporal", "task-queue", "describe",
      "--task-queue", params.name, "--output", "json",
    ]).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // POST /api/v1/admin/compose/fix-memory — RETIRED (no-op stub).
  //
  // This route used to sed-surgery the tenant's rendered docker-compose.yaml
  // to bump OpenClaw's mem_limit. alfred-black ships a single static,
  // version-controlled `docker-compose.yaml` at the repo root — runtime
  // editing of it is no longer correct (the next `git pull` would clobber
  // the patch). Resource sizing is canonical in the committed compose file;
  // change it there. Kept as a clearly-marked no-op so any dashboard caller
  // gets a 200 with an explanation instead of a 404.
  addRoute("POST", "/api/v1/admin/compose/fix-memory", async ({ res }) => {
    sendJson(res, 200, {
      message:
        "Retired on alfred-black. docker-compose.yaml is static + version-controlled — " +
        "adjust resource limits in the committed compose file, not at runtime.",
      changes: [],
      retired: true,
    });
  });
}
