import fs from "node:fs";
import { addRoute } from "../server.js";
import { sendJson, ValidationError } from "../errors.js";
import { dockerComposeCmd, dockerExec, execAsync, sudoExec, parseJsonLines, validateServiceName, COMPOSE_DIR, OPENCLAW_CMD } from "../helpers.js";
import { getVaultContextData, getInboxFiles, VAULT_PATH } from "./vault.js";
import { parseActivityFeed } from "../activity.js";
import { ttlCache } from "../cache.js";

// Activity feed is the most expensive read on the Desk page — it spawns
// `docker compose logs --tail=N alfred` which forks a process per call.
// Coalesce repeat reads (every Desk page-load fires this once, and
// every click invalidates+refetches) onto a single subprocess invocation.
const activityFeedCache = ttlCache<{ items: any[] }>({ ttlMs: 3_000 });

// Host paths for alfred-data and chore directory.
// The ctrl-api container mounts /mnt/encrypted/alfred to the SAME path
// (not to /alfred-data like alfred-learn does), so we use the host
// path directly here. See docker-compose.yaml.njk for the mount config.
const CHORE_GENERATION_AUDIT_LOG = "/mnt/encrypted/alfred/chore-generation-audit.jsonl";
const CHORE_VAULT_DIR = `${VAULT_PATH}/chore`;
const PROMOTION_DRAFTS_DIR = "/mnt/encrypted/alfred/promotion-drafts";

const ENV_PATH = `${COMPOSE_DIR}/.env`;
const OPENCLAW_JSON_PATH = "/mnt/encrypted/openclaw/openclaw.json";
const OPENCLAW_WORKERS_JSON_PATH = "/mnt/encrypted/openclaw-workers/openclaw.json";

// In-memory rate limit for the chore-specific learn restart route. Prevents
// thrashing when an onboarding generates multiple templates and each tries
// to trigger a restart. The limit is intentionally process-local — restarts
// during a stuck/looping container would be visible to ops via container
// uptime anyway.
let _lastLearnRestartAtMs = 0;
const _LEARN_RESTART_MIN_INTERVAL_MS = 30_000;

// Minimal scalar-frontmatter parser for the /audit endpoint. Only handles
// top-level `key: value` and `key: "quoted"` — everything else (nested,
// lists) is ignored. We just need a few summary-bearing keys.
function parseSimpleYaml(raw: string): Record<string, any> {
  const out: Record<string, any> = {};
  for (const line of raw.split("\n")) {
    if (!line || line.startsWith("#")) continue;
    if (/^\s/.test(line)) continue; // skip indented (nested) lines
    const idx = line.indexOf(":");
    if (idx < 1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (val === "null" || val === "~" || val === "") continue;
    out[key] = val;
  }
  return out;
}

// Audit kind classification from filename prefix. The frontmatter `type`
// field is the canonical answer when present; this function exists for
// (a) the pre-stat filename filter (we don't want to read frontmatter
// just to know what kind something is), and (b) a fallback when fm.type
// is missing. Returns "" if nothing matches.
function classifyAuditKind(filename: string): string {
  const KINDS = [
    "steward-action-reversed",
    "steward-action",
    "steward-source-pruned",
    "signal-action",
    "needs_attention_action",
    "desk-action",
    "auto-task-created",
    "daily-digest",
  ];
  for (const k of KINDS) {
    if (filename.startsWith(`${k}-`) || filename === `${k}.md`) return k;
  }
  return "";
}

// Steward-action + steward-source-pruned are auto-generated by the
// steward bot — every existing task gets a health-check ping written
// on every steward pass. 94% of audit volume, ~0% of audit signal.
// Hide by default; surface when ?include_automated=1.
function isAutomatedAuditKind(filename: string): boolean {
  const k = classifyAuditKind(filename);
  return k === "steward-action" || k === "steward-source-pruned";
}

// Cheap per-needs_attention headline lookup. Used by the desk-action
// + needs_attention_action formatters so the summary can read
// "Delegated 'Plex Pass expired — renew to keep it active'" instead of
// the raw needs_attention id. Reads only the linked record's
// frontmatter, returns "" on miss.
function readNeedsAttentionHeadline(refOrId: string): string {
  if (!refOrId) return "";
  // Accept either "needs_attention/<id>.md" or a bare id.
  const id = refOrId
    .replace(/^needs_attention\//, "")
    .replace(/\.md$/, "")
    .trim();
  if (!id) return "";
  try {
    const raw = fs.readFileSync(
      `${VAULT_PATH}/needs_attention/${id}.md`,
      "utf-8",
    );
    const m = /^---\n([\s\S]*?)\n---/.exec(raw);
    if (!m) return "";
    const fm = parseSimpleYaml(m[1]);
    return (
      String(fm.display_headline || fm.action_what || "").trim() || ""
    );
  } catch {
    return "";
  }
}

function quote(s: string): string {
  return s ? `"${s.replace(/"/g, "'")}"` : "";
}

// Build a human sentence for the audit row, dispatching per kind. Each
// formatter assumes the frontmatter we've already read (top-level
// scalars only — see parseSimpleYaml). Falls back to a sane generic
// rendering when a kind isn't specifically handled.
function formatAuditSummary(
  kind: string,
  fm: Record<string, any>,
  filename: string,
): string {
  switch (kind) {
    case "signal-action": {
      const chosen = String(fm.chosen_path || "").trim();
      const reason = String(fm.decision_reason || "").trim();
      const verb =
        chosen === "agent" ? "Dispatched signal to agent" : "Routed signal to your desk";
      return reason ? `${verb} — ${reason.replace(/_/g, " ")}` : verb;
    }

    case "needs_attention_action": {
      // Frontmatter has: action (dispatched/skipped/done), note, target.
      const action = String(fm.action || "").trim();
      const headline = readNeedsAttentionHeadline(
        String(fm.target || ""),
      );
      const verb = action ? toSentenceVerb(action) : "Resolved";
      const subject = headline ? ` ${quote(headline)}` : "";
      const note = String(fm.note || "").trim();
      const noteTail = note ? ` — ${quote(note)}` : "";
      return `${verb}${subject}${noteTail}`;
    }

    case "desk-action":
    case "desk_action": {
      // Frontmatter: action (delegate/defer/delete/do/noise), source,
      // source_id, note.
      const action = String(fm.action || "").trim();
      const source = String(fm.source || "").trim();
      const headline =
        source === "needs_attention"
          ? readNeedsAttentionHeadline(String(fm.source_id || ""))
          : "";
      const verbMap: Record<string, string> = {
        delegate: "Delegated",
        defer: "Deferred",
        delete: "Marked done",
        do: "Took on",
        noise: "Marked noise",
      };
      const verb = verbMap[action] || (action ? toSentenceVerb(action) : "Acted on");
      const subject = headline
        ? ` ${quote(headline)}`
        : source
          ? ` a ${source.replace(/_/g, " ")} card`
          : "";
      const note = String(fm.note || "").trim();
      const noteTail = note ? ` — ${quote(note)}` : "";
      return `${verb}${subject}${noteTail}`;
    }

    case "auto-task-created": {
      const title = String(fm.title || "").trim();
      return title ? `Auto-created task: ${title}` : "Auto-created a task";
    }

    case "daily-digest": {
      // Filename pattern: daily-digest-2026-05-11.md
      const m = filename.match(/^daily-digest-(\d{4})-(\d{2})-(\d{2})\.md$/);
      if (m) {
        try {
          const d = new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);
          return `Daily digest for ${new Intl.DateTimeFormat("en-GB", {
            day: "numeric",
            month: "long",
            year: "numeric",
          }).format(d)}`;
        } catch {
          // fall through
        }
      }
      return "Daily digest";
    }

    case "steward-action": {
      const decision = String(fm.decision || "").trim();
      // Filename has the task slug embedded after the sha — drop the
      // sha + dash, capitalize first letter, replace dashes with spaces.
      const base = filename.replace(/\.md$/, "");
      const m = base.match(
        /^steward-action-\d{4}-\d{2}-\d{2}T[\d-]+Z-[0-9a-f]+-(.+)$/i,
      );
      const subject = m ? sentenceCase(m[1].replace(/-/g, " ")) : "a task";
      const tail = decision
        ? ` — ${decision.replace(/_/g, " ")}`
        : "";
      return `Reviewed "${subject}"${tail}`;
    }

    case "steward-source-pruned":
      return "Pruned stale evidence";

    case "steward-action-reversed":
      return "Reversed a steward action";

    default: {
      // Generic fallback for unknown kinds: try fm summary, fall back
      // to a cleaned-up filename.
      const candidates = [
        fm.summary,
        fm.description,
        fm.headline,
        fm.action_what,
        fm.what,
        fm.title,
        fm.note,
        fm.message,
      ];
      for (const c of candidates) {
        if (typeof c === "string" && c.trim()) return c.trim();
      }
      const base = filename.replace(/\.md$/, "");
      const m = base.match(/^([a-z_]+(?:-action)?)-?\d{4}-\d{2}-\d{2}T[\d-]+Z-(.+)$/i);
      if (m) return `${m[1]} — ${m[2].replace(/-/g, " ")}`;
      return base.replace(/-/g, " ");
    }
  }
}

function sentenceCase(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}

function toSentenceVerb(action: string): string {
  if (!action) return "";
  // Map common past-tense action labels — "dispatched" stays, "done"
  // becomes "Marked done", etc.
  const map: Record<string, string> = {
    dispatched: "Dispatched",
    skipped: "Deferred",
    done: "Marked done",
  };
  return map[action] || sentenceCase(action);
}

export function registerAdminRoutes(): void {
  // --- Containers ---

  // List containers
  addRoute("GET", "/api/v1/admin/containers", async ({ res }) => {
    const stdout = await dockerComposeCmd(["ps", "--format", "json"]);
    sendJson(res, 200, parseJsonLines(stdout));
  });

  // Restart container
  addRoute("POST", "/api/v1/admin/containers/:service/restart", async ({ res, params, req }) => {
    validateServiceName(params.service);
    // Guardrail #3 — self-lockout refusal.
    // Restarting `openclaw` kills the running session; restarting `ctrl-api`
    // kills the API connection mid-request. Both are allowed, but require an
    // explicit opt-in header so an agent can't accidentally lock itself out.
    const SELF_RESTART_SERVICES = ["openclaw", "ctrl-api"];
    if (SELF_RESTART_SERVICES.includes(params.service)) {
      const confirmHeader = req.headers["x-confirm-self-restart"];
      if (confirmHeader !== "yes") {
        sendJson(res, 409, {
          error: `Refusing to restart ${params.service} without X-Confirm-Self-Restart:yes header — this kills the running session or API connection`,
        });
        return;
      }
    }
    await dockerComposeCmd(["restart", params.service]);
    sendJson(res, 200, { message: `Container "${params.service}" restarted` });
  });

  // Stop container
  addRoute("POST", "/api/v1/admin/containers/:service/stop", async ({ res, params }) => {
    validateServiceName(params.service);
    await dockerComposeCmd(["stop", params.service]);
    sendJson(res, 200, { message: `Container "${params.service}" stopped` });
  });

  // Start container
  addRoute("POST", "/api/v1/admin/containers/:service/start", async ({ res, params }) => {
    validateServiceName(params.service);
    await dockerComposeCmd(["start", params.service]);
    sendJson(res, 200, { message: `Container "${params.service}" started` });
  });

  // Container logs (non-streaming)
  addRoute("GET", "/api/v1/admin/containers/:service/logs", async ({ res, params, query }) => {
    validateServiceName(params.service);
    const tail = query.get("tail") ?? "100";
    if (!/^\d+$/.test(tail)) throw new ValidationError("tail must be a number");
    const stdout = await dockerComposeCmd(["logs", "--tail", tail, params.service]);
    sendJson(res, 200, { logs: stdout });
  });

  // Chore-specific alfred-learn restart with rate limiting.
  //
  // The chore generation pipeline (Step 4) calls this after writing a
  // generated template to /alfred-data/user-chores/ so the worker re-imports
  // its module list and picks up the new template. The rate limit prevents
  // thrashing when an onboarding generates multiple templates back-to-back
  // and each tries to trigger a restart.
  //
  // Returns:
  //   200 { ok, restarted_at, ready_after_seconds }
  //   429 { error: "rate limited", retry_after_seconds }
  //   500 { error: <docker error> }
  addRoute("POST", "/api/v1/admin/restart-learn", async ({ res }) => {
    const now = Date.now();
    const elapsed = now - _lastLearnRestartAtMs;
    if (_lastLearnRestartAtMs > 0 && elapsed < _LEARN_RESTART_MIN_INTERVAL_MS) {
      const retryAfter = Math.ceil((_LEARN_RESTART_MIN_INTERVAL_MS - elapsed) / 1000);
      sendJson(res, 429, {
        error: "rate limited",
        retry_after_seconds: retryAfter,
        message: "alfred-learn was restarted recently — wait before triggering another",
      });
      return;
    }
    _lastLearnRestartAtMs = now;

    const startedAt = new Date().toISOString();
    try {
      await dockerComposeCmd(["restart", "alfred-learn"]);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      sendJson(res, 500, { error: "restart failed", details: message });
      return;
    }

    // Best-effort wait for the container to be back in 'running' state.
    // Capped at 60 seconds. We don't poll healthchecks because alfred-learn
    // doesn't have one defined — Temporal heartbeats provide health visibility
    // through other channels.
    const deadline = Date.now() + 60_000;
    let readyAfterMs = 0;
    while (Date.now() < deadline) {
      try {
        const stdout = await dockerComposeCmd([
          "ps",
          "--format",
          "json",
          "alfred-learn",
        ]);
        // Each line is a JSON record. We just need to find the alfred-learn
        // entry and verify its State === "running".
        let isRunning = false;
        for (const line of stdout.split("\n")) {
          const trimmed = line.trim();
          if (!trimmed) continue;
          try {
            const obj = JSON.parse(trimmed);
            if (obj.Service === "alfred-learn" && obj.State === "running") {
              isRunning = true;
              break;
            }
          } catch {
            // ignore non-JSON lines
          }
        }
        if (isRunning) {
          readyAfterMs = Date.now() - now;
          break;
        }
      } catch {
        // ignore poll errors and try again
      }
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    sendJson(res, 200, {
      ok: true,
      restarted_at: startedAt,
      ready_after_seconds: Math.round(readyAfterMs / 1000),
    });
  });

  // --- S4-10: chore generation audit log ---
  //
  // Returns recent entries from /alfred-data/chore-generation-audit.jsonl,
  // which is written by the deploy activity (and the S4-8 generation
  // chain in the onboarding pipeline). One JSON line per deployment
  // event, containing phase/status/module_name/workflow_class_name/
  // source_hash/path/bytes/timestamp.
  //
  // Query params:
  //   limit: max number of entries to return (default 50, cap 500)
  //   since: ISO timestamp — skip entries with earlier timestamps
  //
  // Returns:
  //   200 { entries: Entry[], total_lines_scanned: number, truncated: bool }
  addRoute("GET", "/api/v1/admin/chore-generation-audit", async ({ res, query }) => {
    const AUDIT_LOG_PATH = CHORE_GENERATION_AUDIT_LOG;

    let limit = 50;
    const limitRaw = query.get("limit");
    if (limitRaw !== null) {
      if (!/^\d+$/.test(limitRaw)) {
        throw new ValidationError("limit must be a non-negative integer");
      }
      limit = Math.min(parseInt(limitRaw, 10), 500);
    }

    // Parse the since filter as a unix timestamp (seconds). The audit
    // log stores timestamps as epoch seconds via time.time() in Python.
    let sinceEpoch: number | null = null;
    const sinceRaw = query.get("since");
    if (sinceRaw) {
      const parsed = Date.parse(sinceRaw);
      if (isNaN(parsed)) {
        throw new ValidationError("since must be a valid ISO timestamp");
      }
      sinceEpoch = parsed / 1000;
    }

    if (!fs.existsSync(AUDIT_LOG_PATH)) {
      sendJson(res, 200, {
        entries: [],
        total_lines_scanned: 0,
        truncated: false,
        note: "audit log does not exist yet — no generation events recorded",
      });
      return;
    }

    // Read the whole file (it's rotated by nightly_maintenance so it
    // stays bounded). Parse each line as JSON, filter, and take the
    // last `limit` entries.
    const content = fs.readFileSync(AUDIT_LOG_PATH, "utf-8");
    const lines = content.split("\n").filter((l) => l.trim().length > 0);
    const entries: Array<Record<string, unknown>> = [];
    for (const line of lines) {
      try {
        const entry = JSON.parse(line) as Record<string, unknown>;
        if (sinceEpoch !== null) {
          const ts = entry.timestamp;
          if (typeof ts === "number" && ts < sinceEpoch) continue;
        }
        entries.push(entry);
      } catch {
        // skip malformed lines
      }
    }

    // Return newest-first, capped at limit
    entries.reverse();
    const truncated = entries.length > limit;
    sendJson(res, 200, {
      entries: entries.slice(0, limit),
      total_lines_scanned: lines.length,
      truncated,
    });
  });

  // --- S4-10: emergency-pause-all for chores ---
  //
  // Lists every chore record in vault/chore/ and pauses its Temporal
  // schedule + flips the vault record status to "paused". Used for
  // incident response: if a recent deployment or config change causes
  // chores to misbehave, pause everything at once, investigate, and
  // resume individually.
  //
  // This route is a best-effort batch operation. Failures on individual
  // chores are collected and returned in the response — the overall
  // call still returns 200 as long as SOMETHING paused.
  //
  // Returns:
  //   200 { paused: string[], failed: {slug, error}[], total: number }
  addRoute("POST", "/api/v1/admin/chores/emergency-pause-all", async ({ res }) => {
    const CHORE_DIR = CHORE_VAULT_DIR;
    if (!fs.existsSync(CHORE_DIR)) {
      sendJson(res, 200, {
        paused: [],
        failed: [],
        total: 0,
        note: "no chore directory — nothing to pause",
      });
      return;
    }

    const files = fs
      .readdirSync(CHORE_DIR)
      .filter((name) => name.endsWith(".md"));
    const paused: string[] = [];
    const failed: Array<{ slug: string; error: string }> = [];

    for (const filename of files) {
      const slug = filename.replace(/\.md$/, "");
      try {
        // Pause the Temporal schedule (best-effort). If the schedule
        // doesn't exist we still want to flip the vault status so the
        // state converges.
        try {
          await dockerExec("temporal", [
            "temporal",
            "schedule",
            "toggle",
            "--schedule-id",
            `chore-${slug}`,
            "--pause",
            "--reason",
            "emergency-pause-all",
          ]);
        } catch (err) {
          // Don't bail — still try to flip the vault status below.
          const msg = err instanceof Error ? err.message : String(err);
          if (!msg.includes("not found") && !msg.includes("NotFound")) {
            // Unknown schedule error — record it but continue
            failed.push({ slug, error: `schedule toggle: ${msg}` });
            continue;
          }
        }

        // Flip the vault record status to paused. Uses the same
        // in-place replace pattern as the single pause route in
        // chores.ts — safe because we only touch the status: line
        // inside the frontmatter block.
        const fp = `${CHORE_DIR}/${filename}`;
        const content = fs.readFileSync(fp, "utf-8");
        const end = content.indexOf("\n---", 3);
        if (end === -1) {
          failed.push({ slug, error: "no frontmatter terminator" });
          continue;
        }
        const fmBlock = content.slice(0, end);
        const rest = content.slice(end);
        const updated = fmBlock.replace(/^status:\s*.*$/m, "status: paused");
        fs.writeFileSync(fp, updated + rest, "utf-8");

        paused.push(slug);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        failed.push({ slug, error: msg });
      }
    }

    sendJson(res, 200, {
      paused,
      failed,
      total: files.length,
    });
  });

  // --- S5-3: list pending promotion drafts ---
  //
  // Lists every draft file in /mnt/encrypted/alfred/promotion-drafts/
  // so operators can see what the weekly reflection workflow (S5-2)
  // has staged for potential GitHub PR creation. Each draft is a JSON
  // file written by save_promotion_draft.
  //
  // Returns:
  //   200 {
  //     drafts: [
  //       {
  //         draft_id: string,  // filename stem
  //         module_name: string,
  //         workflow_class_name: string,
  //         pr_title: string,
  //         drafted_at: number,  // epoch seconds
  //         candidate_stats: { total_runs, live_runs, ... },
  //         source_bytes: number,
  //       }
  //     ],
  //     total: number,
  //   }
  addRoute("GET", "/api/v1/admin/chore-promotions", async ({ res }) => {
    if (!fs.existsSync(PROMOTION_DRAFTS_DIR)) {
      sendJson(res, 200, {
        drafts: [],
        total: 0,
        note: "no promotion-drafts directory — reflection workflow hasn't drafted anything yet",
      });
      return;
    }

    const files = fs
      .readdirSync(PROMOTION_DRAFTS_DIR)
      .filter((name) => name.endsWith(".json"));

    const drafts: Array<Record<string, unknown>> = [];
    for (const filename of files) {
      const draftId = filename.replace(/\.json$/, "");
      const fp = `${PROMOTION_DRAFTS_DIR}/${filename}`;
      try {
        const content = fs.readFileSync(fp, "utf-8");
        const parsed = JSON.parse(content) as Record<string, unknown>;
        const pythonSource = typeof parsed.python_source === "string"
          ? parsed.python_source
          : "";
        drafts.push({
          draft_id: draftId,
          module_name: parsed.module_name ?? null,
          workflow_class_name: parsed.workflow_class_name ?? null,
          pr_title: parsed.pr_title ?? null,
          drafted_at: parsed.drafted_at ?? null,
          candidate_stats: parsed.candidate_stats ?? null,
          source_bytes: pythonSource.length,
        });
      } catch (err) {
        // Malformed or unreadable drafts are still listed so operators
        // can manually inspect/delete them. Include the error for context.
        drafts.push({
          draft_id: draftId,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    // Newest first by drafted_at (falls back to filename sort for entries
    // without a timestamp — shouldn't happen but be defensive)
    drafts.sort((a, b) => {
      const ta = typeof a.drafted_at === "number" ? a.drafted_at : 0;
      const tb = typeof b.drafted_at === "number" ? b.drafted_at : 0;
      return tb - ta;
    });

    sendJson(res, 200, { drafts, total: drafts.length });
  });

  // --- Activity Feed ---

  addRoute("GET", "/api/v1/admin/activity", async ({ res, query }) => {
    const limit = parseInt(query.get("limit") ?? "50", 10);
    if (isNaN(limit) || limit < 1) throw new ValidationError("limit must be a positive number");
    const payload = await activityFeedCache.get(`activity:${limit}`, async () => {
      // Fetch 3x more raw lines to account for noise filtering
      const rawTail = Math.min(limit * 3, 1000).toString();
      const stdout = await dockerComposeCmd(["logs", "--no-color", "--tail", rawTail, "alfred"]);
      return { items: parseActivityFeed(stdout, limit) };
    });
    sendJson(res, 200, payload);
  });

  // GET /api/v1/admin/audit — durable audit trail of "every act Alfred
  // has taken on your behalf" as the user-facing /study#audit reads it.
  //
  // Source: vault/event/*.md records (steward-action, signal-action,
  // needs_attention_action, auto-task-created, decision-router etc).
  // 14k+ on a long-running tenant — list by mtime desc and slice to the
  // requested window before reading any frontmatter.
  //
  // NOT the same as /api/v1/admin/activity, which scrapes the alfred
  // container's docker-compose logs (a debug-ops feed). LogsPage stays
  // on /activity; StudyPage's Audit section moves to /audit.
  addRoute("GET", "/api/v1/admin/audit", async ({ res, query }) => {
    const limit = Math.min(
      Math.max(parseInt(query.get("limit") ?? "50", 10) || 50, 1),
      200,
    );
    // ?include_automated=1 lets the principal see the steward bot's
    // health-check pings. Default is to hide them — 94% of david's
    // event records are automated reviews ("yes that task is still
    // alive") that crowd out the actually-interesting moments.
    const includeAutomated = ["1", "true", "yes"].includes(
      (query.get("include_automated") ?? "").toLowerCase(),
    );
    const eventDir = `${VAULT_PATH}/event`;
    let entries: { name: string; mtime: number }[] = [];
    try {
      const names = fs.readdirSync(eventDir);
      for (const name of names) {
        if (!name.endsWith(".md")) continue;
        if (!includeAutomated && isAutomatedAuditKind(name)) continue;
        try {
          const st = fs.statSync(`${eventDir}/${name}`);
          entries.push({ name, mtime: st.mtimeMs });
        } catch {
          // skip unreadable
        }
      }
    } catch {
      sendJson(res, 200, { items: [] });
      return;
    }
    entries.sort((a, b) => b.mtime - a.mtime);
    const top = entries.slice(0, limit);

    const items = top.map((e) => {
      const path = `event/${e.name}`;
      let fm: Record<string, any> = {};
      try {
        const raw = fs.readFileSync(`${eventDir}/${e.name}`, "utf-8");
        const m = /^---\n([\s\S]*?)\n---/.exec(raw);
        if (m) fm = parseSimpleYaml(m[1]);
      } catch {
        // skip frontmatter parse errors — surface what we can
      }
      // Best-effort kind classification from filename prefix +
      // frontmatter type field.
      // Prefer the filename-derived classifier — frontmatter `type` is
      // sometimes generic ("event") even when the filename clearly names
      // the kind (e.g. daily-digest-2026-05-09.md → type:event).
      const kind =
        classifyAuditKind(e.name) ||
        String(fm.type || "").trim() ||
        "event";
      const created =
        String(fm.created || fm.timestamp || "").trim() ||
        new Date(e.mtime).toISOString();
      const summary = formatAuditSummary(kind, fm, e.name);
      return {
        id: e.name.replace(/\.md$/, ""),
        path,
        created,
        kind,
        summary,
      };
    });
    sendJson(res, 200, { items, total: entries.length });
  });

  // --- Config ---

  // Read .env (filtering out AAS_API_KEY)
  addRoute("GET", "/api/v1/admin/config/env", async ({ res }) => {
    let content = "";
    try {
      content = fs.readFileSync(ENV_PATH, "utf-8");
    } catch {
      sendJson(res, 200, { env: {} });
      return;
    }
    const env: Record<string, string> = {};
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx < 0) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const value = trimmed.slice(eqIdx + 1).trim();
      if (key === "AAS_API_KEY") continue; // never expose the API key
      env[key] = value;
    }
    sendJson(res, 200, { env });
  });

  // Update .env (surgical patch — preserves comments, blank lines, ordering)
  addRoute("PATCH", "/api/v1/admin/config/env", async ({ res, body }) => {
    const b = body as Record<string, string | null> | undefined;
    if (!b || typeof b !== "object") throw new ValidationError("Request body must be an object of key-value pairs");

    // Prevent overwriting the API key
    if ("AAS_API_KEY" in b) throw new ValidationError("Cannot modify AAS_API_KEY via API");

    let lines: string[];
    try {
      lines = fs.readFileSync(ENV_PATH, "utf-8").split("\n");
    } catch {
      lines = [];
    }

    const remaining = new Map(Object.entries(b));

    // Update or remove existing lines
    const result = lines.map((line) => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) return line;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx < 0) return line;
      const key = trimmed.slice(0, eqIdx).trim();
      if (!remaining.has(key)) return line;
      const newValue = remaining.get(key);
      remaining.delete(key);
      if (newValue === null) return null; // remove line
      return `${key}=${newValue}`;
    }).filter((line): line is string => line !== null);

    // Append any new keys not already in the file
    for (const [key, value] of remaining) {
      if (value !== null) {
        result.push(`${key}=${value}`);
      }
    }

    const content = result.join("\n");
    fs.writeFileSync(ENV_PATH, content.endsWith("\n") ? content : content + "\n", "utf-8");
    sendJson(res, 200, { message: "Environment updated", keys: Object.keys(b) });
  });

  // Read openclaw.json
  addRoute("GET", "/api/v1/admin/config/openclaw", async ({ res }) => {
    try {
      const content = fs.readFileSync(OPENCLAW_JSON_PATH, "utf-8");
      sendJson(res, 200, JSON.parse(content));
    } catch {
      sendJson(res, 200, {});
    }
  });

  // Update openclaw.json (deep merge)
  addRoute("PATCH", "/api/v1/admin/config/openclaw", async ({ res, body }) => {
    const b = body as Record<string, unknown> | undefined;
    if (!b || typeof b !== "object") throw new ValidationError("Request body must be an object");

    let existing: Record<string, unknown> = {};
    try {
      existing = JSON.parse(fs.readFileSync(OPENCLAW_JSON_PATH, "utf-8"));
    } catch {
      // file doesn't exist yet
    }

    // Guardrail #2 — backup before write, then validate the merged result.
    // Write a timestamped .bak copy so any bad patch can be reverted manually.
    const isoStamp = new Date().toISOString().replace(/[:.]/g, "-");
    const backupPath = OPENCLAW_JSON_PATH.replace(/\.json$/, `.bak-${isoStamp}.json`);
    try {
      if (fs.existsSync(OPENCLAW_JSON_PATH)) {
        fs.copyFileSync(OPENCLAW_JSON_PATH, backupPath);
      }
    } catch (backupErr) {
      // Non-fatal — log but do not block the patch.
      console.warn(`[admin] openclaw.json backup failed: ${backupErr}`);
    }

    const merged = deepMerge(existing, b);

    // Structural validation: must still satisfy openclaw's minimum schema.
    const agentsList = (merged as Record<string, unknown>)["agents"] as Record<string, unknown> | undefined;
    const gatewaySection = (merged as Record<string, unknown>)["gateway"] as Record<string, unknown> | undefined;

    if (!agentsList || !Array.isArray(agentsList["list"]) || (agentsList["list"] as unknown[]).length === 0) {
      sendJson(res, 400, {
        error: "patch would produce invalid openclaw config: agents.list must be a non-empty array",
      });
      return;
    }
    if (!gatewaySection || typeof gatewaySection["auth"] !== "object" || gatewaySection["auth"] === null) {
      sendJson(res, 400, {
        error: "patch would produce invalid openclaw config: gateway.auth must be present",
      });
      return;
    }
    if (!Array.isArray(gatewaySection["tools"]
      ? (gatewaySection["tools"] as Record<string, unknown>)["allow"]
      : undefined)) {
      sendJson(res, 400, {
        error: "patch would produce invalid openclaw config: gateway.tools.allow must be an array",
      });
      return;
    }

    fs.writeFileSync(OPENCLAW_JSON_PATH, JSON.stringify(merged, null, 2) + "\n", "utf-8");
    sendJson(res, 200, { message: "OpenClaw config updated", backup: backupPath });
  });

  // --- Workers ephemeral agents (per-task scoped subagents) ---
  //
  // alfred-learn manages openclaw-workers/openclaw.json indirectly through
  // these endpoints because the alfred-learn container runs with all Linux
  // capabilities dropped (CapEff=0) — it can't traverse the mode-700
  // encrypted volume even as root. ctrl-api has CAP_DAC_OVERRIDE and the
  // same bind-mount, so it owns the writes.
  //
  // Each ephemeral entry is one scoped subagent for one delegated task.
  // ``meta.lastTouchedAt`` is bumped on every write so the openclaw-workers
  // gateway hot-reloads (~10-15s) and the new agent becomes invokable.

  // GET /api/v1/admin/openclaw-workers/agents — list current agent IDs.
  addRoute("GET", "/api/v1/admin/openclaw-workers/agents", async ({ res }) => {
    let cfg: Record<string, unknown> = {};
    try {
      cfg = JSON.parse(fs.readFileSync(OPENCLAW_WORKERS_JSON_PATH, "utf-8"));
    } catch {
      sendJson(res, 404, { error: "workers config not found" });
      return;
    }
    const agents = (cfg.agents as Record<string, unknown> | undefined)?.list;
    const list = Array.isArray(agents) ? agents : [];
    const summary = list.map((a: any) => ({
      id: String(a?.id ?? ""),
      name: String(a?.name ?? ""),
      model: a?.model?.primary ?? null,
      tools_allow_count: Array.isArray(a?.tools?.allow) ? a.tools.allow.length : null,
    }));
    sendJson(res, 200, { agents: summary, count: summary.length });
  });

  // POST /api/v1/admin/openclaw-workers/agents — append (or replace) an
  // agent entry. Body: { id, name?, tools_allow?, model? }.
  addRoute("POST", "/api/v1/admin/openclaw-workers/agents", async ({ res, body }) => {
    const b = body as Record<string, unknown> | undefined;
    if (!b || typeof b !== "object") {
      throw new ValidationError("Request body must be an object");
    }
    const id = String(b.id ?? "").trim();
    if (!id || !/^[a-zA-Z0-9_-]+$/.test(id)) {
      throw new ValidationError("id must be alphanumeric (with - _ allowed)");
    }
    const name = String(b.name ?? `Ephemeral ${id}`);
    const toolsAllow = Array.isArray(b.tools_allow)
      ? (b.tools_allow as unknown[]).map(String)
      : null;
    const model = typeof b.model === "string" && b.model.trim() ? b.model.trim() : null;

    let cfg: Record<string, any> = {};
    try {
      cfg = JSON.parse(fs.readFileSync(OPENCLAW_WORKERS_JSON_PATH, "utf-8"));
    } catch (err) {
      sendJson(res, 500, { error: `workers config not readable: ${(err as Error).message}` });
      return;
    }

    cfg.agents = cfg.agents || {};
    const list: any[] = Array.isArray(cfg.agents.list) ? cfg.agents.list : [];
    // Replace existing entry with same id (defensive — should never happen,
    // but if the cleanup-after-dispatch failed we don't want orphans
    // accumulating duplicates).
    const filtered = list.filter((a) => String(a?.id) !== id);
    const entry: Record<string, any> = {
      id,
      name,
      workspace: "/home/node/.openclaw/workspace",
    };
    if (toolsAllow) entry.tools = { allow: toolsAllow };
    if (model) entry.model = { primary: model };
    entry.subagents = { allowAgents: [] };
    filtered.push(entry);
    cfg.agents.list = filtered;

    cfg.meta = cfg.meta || {};
    cfg.meta.lastTouchedAt = new Date().toISOString().replace(/\.\d+Z$/, ".000Z");

    fs.writeFileSync(
      OPENCLAW_WORKERS_JSON_PATH,
      JSON.stringify(cfg, null, 2) + "\n",
      "utf-8",
    );
    sendJson(res, 201, { id, agent: entry });
  });

  // DELETE /api/v1/admin/openclaw-workers/agents/:id — remove an entry.
  // Idempotent — returns 200 even if the id wasn't there (cleanup ran twice).
  addRoute(
    "DELETE",
    "/api/v1/admin/openclaw-workers/agents/:id",
    async ({ res, params }) => {
      const id = String(params.id ?? "").trim();
      if (!id || !/^[a-zA-Z0-9_-]+$/.test(id)) {
        throw new ValidationError("id must be alphanumeric (with - _ allowed)");
      }
      let cfg: Record<string, any> = {};
      try {
        cfg = JSON.parse(fs.readFileSync(OPENCLAW_WORKERS_JSON_PATH, "utf-8"));
      } catch {
        sendJson(res, 200, { id, removed: false, reason: "config_not_found" });
        return;
      }
      const list: any[] = Array.isArray(cfg.agents?.list) ? cfg.agents.list : [];
      const before = list.length;
      const filtered = list.filter((a) => String(a?.id) !== id);
      if (filtered.length === before) {
        sendJson(res, 200, { id, removed: false, reason: "not_found" });
        return;
      }
      cfg.agents.list = filtered;
      cfg.meta = cfg.meta || {};
      cfg.meta.lastTouchedAt = new Date().toISOString().replace(/\.\d+Z$/, ".000Z");
      fs.writeFileSync(
        OPENCLAW_WORKERS_JSON_PATH,
        JSON.stringify(cfg, null, 2) + "\n",
        "utf-8",
      );
      sendJson(res, 200, { id, removed: true });
    },
  );

  // --- Tailscale ---

  // Tailscale status
  addRoute("GET", "/api/v1/admin/tailscale/status", async ({ res }) => {
    const stdout = await execAsync("tailscale", ["status", "--json"]).then(r => r.stdout);
    sendJson(res, 200, JSON.parse(stdout));
  });

  // Tailscale serve status
  addRoute("GET", "/api/v1/admin/tailscale/serve", async ({ res }) => {
    const stdout = await sudoExec("tailscale", ["serve", "status", "--json"]);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // Regenerate TLS cert
  addRoute("POST", "/api/v1/admin/tailscale/cert", async ({ res }) => {
    const statusRaw = await execAsync("tailscale", ["status", "--json"]).then(r => r.stdout);
    const status = JSON.parse(statusRaw);
    const hostname = status.Self?.DNSName?.replace(/\.$/, "");
    if (!hostname) throw new ValidationError("Could not determine Tailscale hostname");
    await sudoExec("tailscale", ["cert", hostname]);
    sendJson(res, 200, { message: `Certificate regenerated for ${hostname}` });
  });

  // --- Combined dashboard endpoint (single round-trip) ---

  addRoute("GET", "/api/v1/admin/dashboard", async ({ res }) => {
    // Run all async operations in parallel to minimise total wait time
    const [healthResult, containersResult, devicesResult] = await Promise.allSettled([
      execAsync("/opt/alfred/healthcheck.sh", []).then(r => JSON.parse(r.stdout.trim())),
      dockerComposeCmd(["ps", "--format", "json"]).then(s => parseJsonLines(s)),
      dockerExec("openclaw", [...OPENCLAW_CMD, "devices", "list", "--json"]).then(s => JSON.parse(s)),
    ]);

    // Fast synchronous reads
    const vaultRaw = getVaultContextData();
    const inboxFiles = getInboxFiles();
    let openclawCfg: unknown = {};
    try {
      openclawCfg = JSON.parse(fs.readFileSync(OPENCLAW_JSON_PATH, "utf-8"));
    } catch {
      // file may not exist yet
    }

    sendJson(res, 200, {
      health: healthResult.status === "fulfilled" ? healthResult.value : null,
      containers: containersResult.status === "fulfilled" ? containersResult.value : null,
      devices: devicesResult.status === "fulfilled" ? devicesResult.value : null,
      vault: vaultRaw,
      inbox: { files: inboxFiles },
      openclawCfg,
    });
  });

  // --- Health ---

  addRoute("GET", "/api/v1/admin/health", async ({ res }) => {
    const stdout = await execAsync("/opt/alfred/healthcheck.sh", []).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout.trim()));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // --- Diagnostics ---

  // Echo request headers back (to verify what actually arrives at the ctrl API)
  addRoute("GET", "/api/v1/admin/debug/headers", async ({ req, res }) => {
    sendJson(res, 200, {
      method: req.method,
      url: req.url,
      httpVersion: req.httpVersion,
      headers: req.headers,
      terminalReady: (globalThis as any).__terminalReady ?? "not_set",
      terminalError: (globalThis as any).__terminalError ?? null,
    });
  });

  // --- System info ---

  addRoute("GET", "/api/v1/admin/system/info", async ({ res }) => {
    const [uptimeResult, diskResult, memResult] = await Promise.all([
      execAsync("uptime", ["-p"]).then(r => r.stdout.trim()).catch(() => "unknown"),
      execAsync("df", ["-h", "/mnt/encrypted"]).then(r => r.stdout.trim()).catch(() => "unknown"),
      execAsync("free", ["-m"]).then(r => r.stdout.trim()).catch(() => "unknown"),
    ]);
    sendJson(res, 200, { uptime: uptimeResult, disk: diskResult, memory: memResult });
  });

  // --- Backups ---

  // Trigger backup (fire-and-forget)
  addRoute("POST", "/api/v1/admin/backups/trigger", async ({ res }) => {
    execAsync("sudo", ["bash", "/opt/alfred/backup.sh"], 600_000).catch((err) => {
      console.error("Backup failed:", err.message);
    });
    sendJson(res, 202, { message: "Backup triggered" });
  });

  // List backup snapshots
  addRoute("GET", "/api/v1/admin/backups/snapshots", async ({ res }) => {
    const stdout = await execAsync("bash", [
      "-c",
      "set -a && source /opt/alfred/restic.env && restic snapshots --json",
    ], 60_000).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // --- Temporal cluster ---

  addRoute("GET", "/api/v1/admin/temporal/cluster", async ({ res }) => {
    const stdout = await execAsync("docker", [
      "compose", "-f", `${COMPOSE_DIR}/docker-compose.yaml`,
      "exec", "-T", "temporal", "temporal", "operator", "cluster", "describe", "--output", "json",
    ]).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // Task queue describe
  addRoute("GET", "/api/v1/admin/temporal/task-queues/:name", async ({ res, params }) => {
    const stdout = await execAsync("docker", [
      "compose", "-f", `${COMPOSE_DIR}/docker-compose.yaml`,
      "exec", "-T", "temporal", "temporal", "task-queue", "describe",
      "--task-queue", params.name, "--output", "json",
    ]).then(r => r.stdout);
    try {
      sendJson(res, 200, JSON.parse(stdout));
    } catch {
      sendJson(res, 200, { raw: stdout.trim() });
    }
  });

  // Fix OpenClaw memory limit in docker-compose.yaml (safe, non-destructive)
  addRoute("POST", "/api/v1/admin/compose/fix-memory", async ({ res }) => {
    const fs = await import("node:fs");
    const composePath = `${COMPOSE_DIR}/docker-compose.yaml`;
    let content: string;
    try {
      content = fs.readFileSync(composePath, "utf-8");
    } catch (err) {
      sendJson(res, 500, { error: `Cannot read compose file: ${err}` });
      return;
    }

    const changes: string[] = [];

    // Fix openclaw mem_limit: 2g -> 4g
    if (content.includes("mem_limit: 2g")) {
      content = content.replace(/mem_limit: 2g/g, "mem_limit: 4g");
      changes.push("mem_limit: 2g -> 4g (all services)");
    }

    // Add NODE_OPTIONS if not in environment block for openclaw
    if (!content.includes("NODE_OPTIONS")) {
      content = content.replace(
        /- OPENCLAW_GATEWAY_TOKEN_FILE=/,
        "- NODE_OPTIONS=--max-old-space-size=3072\n      - OPENCLAW_GATEWAY_TOKEN_FILE="
      );
      changes.push("Added NODE_OPTIONS=--max-old-space-size=3072 to openclaw");
    }

    // Fix healthcheck retries
    content = content.replace(
      /retries: 10\n(\s+)start_period: 30s/g,
      "retries: 30\n$1start_period: 60s"
    );

    if (changes.length === 0) {
      sendJson(res, 200, { message: "No changes needed — compose already up to date", changes: [] });
      return;
    }

    // Write updated compose
    fs.writeFileSync(composePath, content, "utf-8");

    // Respond immediately, recreate in background
    sendJson(res, 200, { message: "Compose updated. OpenClaw recreating in background.", changes });

    dockerComposeCmd(["up", "-d", "--no-deps", "--force-recreate", "openclaw"]).catch((err) => {
      console.error("Failed to recreate openclaw after compose fix:", err);
    });
  });
}

function deepMerge(target: Record<string, unknown>, source: Record<string, unknown>): Record<string, unknown> {
  const result = { ...target };
  for (const [key, value] of Object.entries(source)) {
    if (
      value && typeof value === "object" && !Array.isArray(value) &&
      result[key] && typeof result[key] === "object" && !Array.isArray(result[key])
    ) {
      result[key] = deepMerge(result[key] as Record<string, unknown>, value as Record<string, unknown>);
    } else {
      result[key] = value;
    }
  }
  return result;
}
