import fs from "node:fs";
import { addRoute } from "../server.js";
import { sendJson, ValidationError } from "../errors.js";
import { dockerComposeCmd, COMPOSE_DIR } from "../helpers.js";
import { invalidateModelCatalogCache } from "./models.js";

const ENV_PATH = `${COMPOSE_DIR}/.env`;

interface CredentialDef {
  key: string;
  label: string;
  description: string;
  used_by: string[];
}

const KNOWN_CREDENTIALS: CredentialDef[] = [
  {
    key: "OPENROUTER_API_KEY",
    label: "OpenRouter",
    description: "Routes to 200+ models. Primary provider for all OpenClaw agents",
    used_by: ["OpenClaw agents (all)", "Surveyor (labeler)", "Surveyor (embedder, if configured)"],
  },
  {
    key: "ANTHROPIC_API_KEY",
    label: "Anthropic",
    description: "Direct Claude access. Required when using anthropic/ models directly",
    used_by: ["OpenClaw agents (if model requires it)"],
  },
  {
    key: "OPENAI_API_KEY",
    label: "OpenAI",
    description: "GPT-4, GPT-4o, gpt-realtime. Required for voice calls — voice-bridge uses gpt-realtime over the Twilio Media Streams socket.",
    used_by: ["voice-bridge (gpt-realtime)", "Hermes agents (if model requires it)"],
  },
  {
    key: "XAI_API_KEY",
    label: "xAI",
    description: "Grok models from xAI",
    used_by: ["OpenClaw agents (if model requires it)"],
  },
  {
    key: "GOOGLE_API_KEY",
    label: "Google",
    description: "Gemini and other Google AI models",
    used_by: ["OpenClaw agents (if model requires it)"],
  },
  {
    key: "KIMI_API_KEY",
    label: "Kimi Code",
    description: "Moonshot Kimi Code subscription. Required for the main agent when set to a kimi/* model (kimi/kimi-code, kimi/k2p5). Get a key at https://platform.moonshot.ai/console/keys",
    used_by: ["OpenClaw agents (if model requires it)"],
  },
  // Vaultwarden bootstrap entries — only the four values vault-init needs
  // to log in to the local Vaultwarden and pull every other secret. Listed
  // here so dashboard surfaces them (and shows masked values), but rotation
  // is rare. BW_PASSWORD specifically is dangerous to edit directly — see
  // each description.
  {
    key: "VAULTWARDEN_ADMIN_TOKEN",
    label: "Vaultwarden admin token",
    description: "Bearer token gating Vaultwarden's /admin panel. Generated by the provisioner. To rotate: generate a new value, save here, restart the vaultwarden container.",
    used_by: ["vaultwarden container (read at boot)", "ctrl-api setupVaultwarden"],
  },
  {
    key: "BW_USER",
    label: "Vaultwarden user (Sir's email)",
    description: "Sir's Vaultwarden account email — the one used at /admin/invite during provisioning. Rarely changes (only if Sir's owner_email rotates).",
    used_by: ["vault-init container"],
  },
  {
    key: "BW_PASSWORD",
    label: "Vaultwarden master password",
    description: "Sir's Vaultwarden master password. DANGER: Vaultwarden's master password also encrypts the vault; changing this value here without ALSO doing 'Change Master Password' in Vaultwarden's web UI will brick vault-init. Treat as service credential; rotate only if leaked.",
    used_by: ["vault-init container (bw login + unlock)"],
  },
  {
    key: "BW_SERVER_URL",
    label: "Vaultwarden server URL",
    description: "Internal compose-network URL vault-init points at (typically http://vaultwarden:80). Editable for debugging only.",
    used_by: ["vault-init container"],
  },
  // AgentPhone / voice-bridge credentials (C15 phone provision). The phone
  // wizard persists these via POST /api/v1/phone/provision, but they are
  // listed here so the credentials surface can mask + rotate them too. OpenAI
  // is already covered by OPENAI_API_KEY above (the voice-bridge reads the
  // same key for the Realtime API).
  {
    key: "TWILIO_ACCOUNT_SID",
    label: "Twilio Account SID",
    description: "Twilio account SID used by the SaaS to send SMS + initiate calls on this tenant's behalf. Provisioned via the phone wizard.",
    used_by: ["SaaS Twilio internal endpoints", "voice-bridge"],
  },
  {
    key: "TWILIO_AUTH_TOKEN",
    label: "Twilio Auth Token",
    description: "Twilio auth token paired with the account SID. Treat as a service credential; rotate if leaked.",
    used_by: ["SaaS Twilio internal endpoints", "voice-bridge"],
  },
  {
    key: "TWILIO_PHONE_NUMBER",
    label: "Twilio phone number",
    description: "The E.164 phone number Alfred answers/sends from. Read by phone.ts (readInstanceMeta) for outbound SMS/calls.",
    used_by: ["ctrl-api phone routes", "voice-bridge"],
  },
  {
    key: "VOICE_BRIDGE_INTERNAL_TOKEN",
    label: "Voice-bridge internal token",
    description: "Shared secret between ctrl-api/voice-bridge and the SaaS internal Twilio endpoints (Bearer auth). Generated at provision time.",
    used_by: ["ctrl-api phone routes", "voice-bridge", "SaaS internal endpoints"],
  },
  // AgentMail webhook secret. AgentMail does not sign its webhooks, so the
  // public `/api/v1/channels/email/inbound` endpoint validates a shared
  // `?token=` query param against this value. Bake the token into the URL
  // configured in the AgentMail console. Rotate by setting a new value here
  // and updating the console — old value stops accepting immediately.
  {
    key: "AGENTMAIL_WEBHOOK_TOKEN",
    label: "AgentMail webhook token",
    description: "Shared secret for inbound AgentMail webhook delivery. The agentmail.to console webhook URL must include ?token=<this value>. Generate with `openssl rand -hex 32` and update both places.",
    used_by: ["ctrl-api /api/v1/channels/email/inbound"],
  },
];

/** Protected keys that cannot be modified via this endpoint. */
const PROTECTED_KEYS = new Set(["AAS_API_KEY"]);

/** Mask a secret value: show first 8 and last 4 chars. */
function maskValue(value: string): string {
  if (value.length <= 12) return "****";
  return value.slice(0, 8) + "..." + value.slice(-4);
}

/** Read .env file into a key-value map. */
function readEnv(): Record<string, string> {
  let content = "";
  try {
    content = fs.readFileSync(ENV_PATH, "utf-8");
  } catch {
    return {};
  }
  const env: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx < 0) continue;
    env[trimmed.slice(0, eqIdx).trim()] = trimmed.slice(eqIdx + 1).trim();
  }
  return env;
}

/**
 * Surgically update specific keys in the .env file, preserving all
 * comments, blank lines, ordering, and unrelated keys.
 * Set a value to null to remove that key.
 */
export function patchEnv(updates: Record<string, string | null>): void {
  let lines: string[];
  try {
    lines = fs.readFileSync(ENV_PATH, "utf-8").split("\n");
  } catch {
    lines = [];
  }

  const remaining = new Map(Object.entries(updates));

  // Update or remove existing lines
  const result = lines.map((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return line;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx < 0) return line;
    const key = trimmed.slice(0, eqIdx).trim();
    if (!remaining.has(key)) return line;
    const newValue = remaining.get(key);
    remaining.delete(key);
    if (newValue === null) return null; // remove line
    return `${key}=${newValue}`;
  }).filter((line): line is string => line !== null);

  // Append any new keys not already in the file
  for (const [key, value] of remaining) {
    if (value !== null) {
      result.push(`${key}=${value}`);
    }
  }

  // Ensure trailing newline
  const content = result.join("\n");
  fs.writeFileSync(ENV_PATH, content.endsWith("\n") ? content : content + "\n", "utf-8");
}

export function registerCredentialRoutes(): void {
  // GET /api/v1/admin/credentials — list known credentials with masked values
  addRoute("GET", "/api/v1/admin/credentials", async ({ res }) => {
    const env = readEnv();

    const credentials = KNOWN_CREDENTIALS.map((def) => {
      const value = env[def.key];
      return {
        key: def.key,
        label: def.label,
        description: def.description,
        set: !!value,
        masked: value ? maskValue(value) : null,
        used_by: def.used_by,
      };
    });

    sendJson(res, 200, { credentials });
  });

  // PATCH /api/v1/admin/credentials — update credential values
  addRoute("PATCH", "/api/v1/admin/credentials", async ({ res, body }) => {
    const b = body as Record<string, string | null> | undefined;
    if (!b || typeof b !== "object") {
      throw new ValidationError("Request body must be an object of key-value pairs");
    }

    // Validate all keys are known credentials
    const knownKeys = new Set(KNOWN_CREDENTIALS.map((d) => d.key));
    for (const key of Object.keys(b)) {
      if (PROTECTED_KEYS.has(key)) {
        throw new ValidationError(`Cannot modify protected key: ${key}`);
      }
      if (!knownKeys.has(key)) {
        throw new ValidationError(`Unknown credential key: ${key}. Known keys: ${[...knownKeys].join(", ")}`);
      }
    }

    const updates: Record<string, string | null> = {};
    for (const [key, value] of Object.entries(b)) {
      if (value === null) {
        updates[key] = null;
      } else {
        if (typeof value !== "string") {
          throw new ValidationError(`Value for ${key} must be a string or null`);
        }
        updates[key] = value;
      }
    }

    patchEnv(updates);

    // Drop the in-memory model catalog cache so the next GET /admin/models
    // reflects the newly-available (or removed) providers immediately
    // instead of waiting up to an hour for the cache to expire.
    invalidateModelCatalogCache();

    // Choose which services to recreate based on which credentials changed.
    // Every credential rotation needs openclaw/hermes + alfred picked up
    // (their env is the LLM provider keys). OPENAI_API_KEY ALSO drives
    // voice-bridge — without this, setting the key via the /channels Phone
    // card surfaces "saved" but the container keeps crash-looping until the
    // next manual restart.
    const changedKeys = new Set(Object.keys(updates));
    const services = ["openclaw", "alfred"];
    if (changedKeys.has("OPENAI_API_KEY")) {
      services.push("voice-bridge");
    }

    // Respond immediately, then restart only the containers that need
    // the new API keys. CRITICAL: ctrl-api also uses env_file: .env,
    // so `docker compose up -d` would recreate ALL containers including
    // ctrl-api itself — causing a 502 cascade. Instead, selectively
    // recreate using --no-deps to prevent Docker Compose from also
    // recreating dependencies (ctrl-api).
    sendJson(res, 200, {
      message: "Credentials updated. Services are restarting (may take ~30s).",
      restarted: services,
    });

    // Fire-and-forget: recreate each service sequentially so we don't
    // contend with health-checks. Sequential = openclaw → alfred → (voice).
    (async () => {
      for (const svc of services) {
        try {
          await dockerComposeCmd(["up", "-d", "--no-deps", "--force-recreate", svc]);
        } catch (err) {
          console.error(`Background restart of ${svc} failed:`, err);
        }
      }
    })();
  });

  // POST /api/v1/admin/vault/refresh — pull every secret out of Vaultwarden,
  // rewrite .env, and (optionally) restart impacted services. The dashboard's
  // "rotate secret" flow calls this after Sir edits an item in the Vaultwarden
  // web UI: one click instead of SSH + two compose commands.
  //
  // Body shape:
  //   {
  //     services?: string[]   // services to recreate after vault-init runs.
  //                           // Defaults to ["openclaw", "alfred"] which
  //                           // matches PATCH /admin/credentials. Pass
  //                           // explicitly when rotating tenant-specific
  //                           // creds (e.g. ["sure-web", "sure-worker"]
  //                           // for Sure DB password rotation).
  //   }
  //
  // Behaviour:
  //   1. Refuses if VAULTWARDEN_ADMIN_TOKEN is missing (= tenant not migrated)
  //   2. Runs `docker compose run --rm vault-init` synchronously and waits
  //      for exit. vault-init exit codes:
  //        0 → secrets fetched + .env rewritten
  //        1 → vaultwarden unreachable (soft — last-good .env stays)
  //        2 → data error (.env unchanged)
  //        3 → config error (missing env vars)
  //      We surface the exit code; only on 0 do we proceed to restart.
  //   3. Recreates impacted services with --no-deps + --force-recreate so
  //      ctrl-api itself isn't touched (would 502 the response we just sent).
  //   4. Returns synchronously after vault-init exits but BEFORE the restart
  //      finishes — same fire-and-forget pattern as PATCH /admin/credentials.
  addRoute("POST", "/api/v1/admin/vault/refresh", async ({ res, body }) => {
    // Cheap pre-flight: refuse if vaultwarden's bootstrap secrets aren't in
    // .env yet. Running vault-init without them would just exit 3 and
    // surface a confusing error.
    const envContents = fs.readFileSync(ENV_PATH, "utf8");
    if (!/^VAULTWARDEN_ADMIN_TOKEN=/m.test(envContents)) {
      sendJson(res, 409, {
        error: "Vaultwarden not provisioned on this tenant — VAULTWARDEN_ADMIN_TOKEN missing from .env. Run setupVaultwarden via the provisioner first.",
      });
      return;
    }

    const b = (body ?? {}) as { services?: unknown };
    let services: string[] = ["openclaw", "alfred"];
    if (b.services !== undefined) {
      if (!Array.isArray(b.services)) {
        throw new ValidationError("services must be an array of service names");
      }
      services = b.services.map((s) => {
        if (typeof s !== "string") {
          throw new ValidationError("each service must be a string");
        }
        // Same charset rule as validateServiceName — keeps shell-injection
        // surface flat.
        if (!/^[a-zA-Z0-9_-]+$/.test(s)) {
          throw new ValidationError(`Invalid service name: ${s}`);
        }
        return s;
      });
      // Refuse self-restart unless explicitly opted in via the same header
      // pattern other admin routes use. ctrl-api restarting itself mid-
      // request would 502 the response.
      const SELF_LOCKOUT = ["ctrl-api"];
      const hits = services.filter((s) => SELF_LOCKOUT.includes(s));
      if (hits.length > 0) {
        sendJson(res, 409, {
          error: `Refusing to restart ${hits.join(", ")} via vault refresh — would kill the API connection mid-request. Restart these manually via SSH or the per-service /admin/containers/:service/restart route.`,
        });
        return;
      }
    }

    // Run vault-init synchronously. `docker compose run --rm vault-init`
    // re-uses the existing service definition (env_file, depends_on, volumes)
    // but exits when the script does, leaving no zombie container. The
    // service is restart: "no" in the template so this doesn't create a
    // long-lived process.
    let vaultInitOutput = "";
    let vaultInitExitCode = 0;
    try {
      vaultInitOutput = await dockerComposeCmd(["run", "--rm", "vault-init"]);
    } catch (err: unknown) {
      // dockerComposeCmd → execAsync wraps non-zero exit in ExecError. Pull
      // the exit code out of the message; the helper doesn't expose it
      // directly but the format is "docker failed (CODE): ..."
      const msg = err instanceof Error ? err.message : String(err);
      const match = /failed \((\d+)\)/.exec(msg);
      vaultInitExitCode = match ? parseInt(match[1], 10) : -1;
      vaultInitOutput = msg;
    }

    if (vaultInitExitCode !== 0) {
      sendJson(res, 502, {
        error: "vault-init failed; .env was NOT rewritten and no services were restarted",
        exit_code: vaultInitExitCode,
        // Trim to keep the response payload reasonable; full output is in
        // `docker compose logs vault-init` if Sir wants the detail.
        output: vaultInitOutput.slice(-2000),
      });
      return;
    }

    // Respond immediately, then restart in the background — same pattern as
    // PATCH /admin/credentials. The restart is `up -d --no-deps
    // --force-recreate` per service, sequential so dependent containers
    // don't trample each other on startup.
    invalidateModelCatalogCache();
    sendJson(res, 200, {
      message: "Vault refreshed. Services are restarting (may take ~30s).",
      vault_init_output: vaultInitOutput.slice(-1000),
      restarted: services,
    });

    (async () => {
      for (const svc of services) {
        try {
          await dockerComposeCmd(["up", "-d", "--no-deps", "--force-recreate", svc]);
        } catch (err) {
          console.error(`Vault refresh: restart of ${svc} failed:`, err);
        }
      }
    })();
  });
}
